      SUBROUTINE QQBJJBJJ (P1,ANS)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C
C FOR PROCESS : u u~ -> b w+ b~ mu- vm~
C
C Crossing   1 is u u~ -> b w+ b~ mu- vm~
      IMPLICIT NONE
C
C CONSTANTS
C
      Include "genps.inc"
      INTEGER    NCOMB,    NCROSS
      PARAMETER (NCOMB=16, NCROSS=1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C
C ARGUMENTS
C
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C
C LOCAL VARIABLES
C
      INTEGER NHEL(NEXTERNAL,NCOMB), NTRY
      REAL*8 T, P(0:3,NEXTERNAL)
      REAL*8 MEQQBJJBJJ
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL), I
      INTEGER NGRAPHS
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_q/  amp2,       jamp2
      DATA NGRAPHS /6/
      DATA jamp2(0) /1/
      DATA (NHEL(IHEL,  1),IHEL=1, 8) /-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  2),IHEL=1, 8) /-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  3),IHEL=1, 8) /-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  4),IHEL=1, 8) /-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  5),IHEL=1, 8) /-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  6),IHEL=1, 8) /-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  7),IHEL=1, 8) /-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  8),IHEL=1, 8) /-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  9),IHEL=1, 8) / 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 10),IHEL=1, 8) / 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 11),IHEL=1, 8) / 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 12),IHEL=1, 8) / 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 13),IHEL=1, 8) / 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 14),IHEL=1, 8) / 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 15),IHEL=1, 8) / 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 16),IHEL=1, 8) / 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (  IC(IHEL,  1),IHEL=1, 8) / 1, 2, 3, 4, 5, 6, 7, 8/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  36/
C --------
C USER SET
C --------
      INTEGER KHEL
      COMMON/HEL/KHEL
      INTEGER HHEL(NEXTERNAL)
      COMMON/HEL2/HHEL
C ----------
C BEGIN CODE
C ----------
      DO IPROC = 1, NCROSS
         CALL SWITCHMOM (P1,P,IC(1,IPROC),JC,NEXTERNAL)
         DO IHEL = 1, NEXTERNAL
            JC(IHEL) = +1
         ENDDO
         ANS(IPROC) = 0D0
         IF (KHEL.EQ.0) THEN
            DO IHEL = 1, NCOMB
               T = MEQQBJJBJJ (P,NHEL(1,IHEL),JC(1))
               ANS(IPROC) = ANS(IPROC) + T
            ENDDO
         ELSE
            ANS(IPROC) =  MEQQBJJBJJ (P,NHEL(1,KHEL),JC(1))
            DO I = 1,NEXTERNAL
               HHEL(I) = NHEL(I,KHEL)
            ENDDO
         ENDIF
         ANS(IPROC) = ANS(IPROC) / DBLE(IDEN(IPROC))
      ENDDO
      END
C
C
      REAL*8 FUNCTION MEQQBJJBJJ (P,NHEL,IC)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C
C FOR PROCESS : u u~ -> b w+ b~ mu- vm~
C
      IMPLICIT NONE
C
C CONSTANTS
C
      INTEGER    NGRAPHS,    NEIGEN
      PARAMETER (NGRAPHS=   6,NEIGEN=  1)
      include "genps.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=   18, NCOLOR=   1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C
C ARGUMENTS
C
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C
C LOCAL VARIABLES
C
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS)
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_q/  amp2,       jamp2
      include "coupl_sm.inc"
C ----------
C COLOR DATA
C ----------
      DATA Denom(1  )/            1/
      DATA (CF(i,1  ),i=1  ,1  ) /    18/
C     T[ 3, 1]T[ 2, 6]
C
C --------
C USER SET
C --------
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      COMPLEX*16 OV1,OV2
      DOUBLE COMPLEX GAMMA
      DOUBLE PRECISION CORR,COR
      EXTERNAL CORR
      DOUBLE PRECISION FNR(0:2)
      DATA FNR/0.,1.,1./
      include 'thr.inc'
      include 'kin_functions.inc'
      DOUBLE PRECISION PW1(0:3),PW2(0:3)
      DOUBLE PRECISION RTC(NCOLOR)
      COMMON/COL/RTC
C ----------
C BEGIN CODE
C ----------
      CALL IXXXXX (P(0, 1),ZERO   ,NHEL(1),+1*IC(1),W(1, 1)) ! q
      CALL OXXXXX (P(0, 2),ZERO   ,NHEL(2),-1*IC(2),W(1, 2)) ! q~
      CALL OXXXXX (P(0, 3),BMASS  ,NHEL(3),+1*IC(3),W(1, 3)) ! b
      CALL IXXXXX (P(0, 4),ZERO   ,NHEL(4),-1*IC(4),W(1, 7)) ! d~
      CALL OXXXXX (P(0, 5),ZERO   ,NHEL(5),+1*IC(5),W(1, 8)) ! u
      CALL IXXXXX (P(0, 6),BMASS  ,NHEL(6),-1*IC(6),W(1, 5)) ! b~
      CALL OXXXXX (P(0, 7),ZERO   ,NHEL(7),+1*IC(7),W(1, 9)) ! d
      CALL IXXXXX (P(0, 8),ZERO   ,NHEL(8),-1*IC(8),W(1,10)) ! u~
      CALL JIOXXX (W(1, 7),W(1, 8),GWF,WMASS,WWIDTH,W(1, 4)) ! W+*
      CALL JIOXXX (W(1,10),W(1, 9),GWF,WMASS,WWIDTH,W(1, 6)) ! W-*
      CALL FVOXXX (W(1, 3),W(1, 4),GWF,TMASS,TWIDTH,W(1,11)) ! t*
      CALL FVIXXX (W(1, 5),W(1, 6),GWF,TMASS,TWIDTH,W(1,12)) ! t~*
      DO I = 0, 3
         PW1(I) = P(I, 4) + P(I, 5)
         PW2(I) = P(I, 7) + P(I, 8)
      ENDDO
      MT1S = SumDot(P(0,3),PW1(0),+1D0)
      MT2S = SumDot(P(0,6),PW2(0),+1D0)
      S    = SumDot(P(0,1),P(0,2),+1D0)
      IF (ITR.EQ.0) THEN
         COR = 1D0
      ELSEIF (ITR.EQ.1) THEN
         COR = CORR (MT1S,MT2S,TMASS,TWIDTH,gfermi,WMASS,BMASS)
      ENDIF
C...  Resonant diagram
      DO I = 1, NGRAPHS
         AMP(I) = (0D0,0D0)
      ENDDO
      CALL JIOXXX (W(1,1),W(1,2),GG,ZERO,ZERO,W(1,13)) ! g*
      CALL IOVXXX (W(1,12),W(1,11),W(1,13),GG,AMP(5))
      CALL GRNMOD (GAMMA,MT1S,MT2S,S,TMASS,2,IGRN)
      AMP(5) = AMP(5) * ( COR*GAMMA + (1D0-COR)*FNR(INR) )
      IF (INR.EQ.0) GOTO 100
C...  Non-Resonant diagram
      CALL FVOXXX (W(1,3),W(1,4),GWF,TMASS,TWIDTH,W(1,16)) ! t*
      CALL FVIXXX (W(1,5),W(1,6),GWF,TMASS,TWIDTH,W(1,17)) ! t~*
      CALL FVIXXX (W(1,1 ),W(1,4 ),GWF,ZERO ,ZERO  ,W(1,7 ))
      CALL JIOXXX (W(1,5 ),W(1,3 ),GG ,ZERO ,ZERO  ,W(1,8 ))
      CALL FVIXXX (W(1,7 ),W(1,8 ),GG ,ZERO ,ZERO  ,W(1,9 ))
      CALL IOVXXX (W(1,9 ),W(1,2 ),W(1,6),GWF,AMP(1))
      CALL FVOXXX (W(1,2 ),W(1,8 ),GG ,ZERO ,ZERO  ,W(1,10))
      CALL IOVXXX (W(1,7 ),W(1,10),W(1,6),GWF,AMP(2))
      CALL FVIXXX (W(1,1 ),W(1,8 ),GG ,ZERO ,ZERO  ,W(1,11))
      CALL FVIXXX (W(1,11),W(1,4 ),GWF,ZERO ,ZERO  ,W(1,12))
      CALL IOVXXX (W(1,12),W(1,2 ),W(1,6),GWF,AMP(3))
      CALL FVOXXX (W(1,3 ),W(1,13),GG ,BMASS,ZERO  ,W(1,14))
      CALL FVOXXX (W(1,14),W(1,4 ),GWF,TMASS,TWIDTH,W(1,15))
      CALL IOVXXX (W(1,5 ),W(1,15),W(1,6),GWF,AMP(4))
*     CALL IOVXXX (TB,TP,W(1,13),GG,AMP(5))
      CALL FVIXXX (W(1,5 ),W(1,13),GG ,BMASS,ZERO  ,W(1,18))
      CALL IOVXXX (W(1,18),W(1,16),W(1,6),GWF,AMP(6))
C.....
      IF (INR.EQ.2) THEN        ! OFS
         OV1 = DCMPLX(MT1S-TMASS**2,0D0 ) /
     -        DCMPLX( MT1S-TMASS**2,TMASS*TWIDTH)
         OV2 = DCMPLX(MT2S-TMASS**2,0D0 ) /
     -        DCMPLX( MT2S-TMASS**2,TMASS*TWIDTH)
         AMP( 1) = AMP( 1) * OV1*OV2
         AMP( 2) = AMP( 2) * OV1*OV2
         AMP( 3) = AMP( 3) * OV1*OV2
         AMP( 4) = AMP( 4) * OV1*OV2
         AMP( 6) = AMP( 6) * OV1*OV2
      ENDIF
C.....
 100  CONTINUE
      JAMP(1) = - AMP(1) - AMP(2) - AMP(3) - AMP(4) - AMP(5) - AMP(6)
      MEQQBJJBJJ = 0D0
      DO I = 1, NCOLOR
         ZTEMP = (0D0,0D0)
         DO J = 1, NCOLOR
            ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
         ENDDO
         MEQQBJJBJJ = MEQQBJJBJJ + ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO
      Do I = 1, NCOLOR
         Jamp2(i)=Jamp2(i)+Jamp(i)*dconjg(Jamp(i))
      Enddo
      DO I = 1,NCOLOR
         RTC(I) = jamp2(I) / (jamp2(1)+jamp2(2))
      ENDDO
      END
