      SUBROUTINE GGBWBW (P1,ANS,ICLR)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C
C FOR PROCESS : g g -> b w+ b~ w-
C
C Crossing   1 is g g -> b w+ b~ w-
      IMPLICIT NONE
C
C CONSTANTS
C
      Include "genps.inc"
      INTEGER                 NCOMB,     NCROSS
      PARAMETER (             NCOMB= 144, NCROSS=  1)
C
C ARGUMENTS
C
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C
C LOCAL VARIABLES
C
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T, P(0:3,NEXTERNAL)
      REAL*8 P2(0:3,NEXTERNAL)
      REAL*8 MEGGBWBW
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL), I,ICLR
      INTEGER NGRAPHS
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_g/  amp2,       jamp2

      DATA NGRAPHS /    15/
      DATA jamp2(0) /   2/
      DATA (NHEL(IHEL,   1),IHEL=1, 6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1, 6) /-1,-1,-1,-1,-1, 0/
      DATA (NHEL(IHEL,   3),IHEL=1, 6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,   4),IHEL=1, 6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,   5),IHEL=1, 6) /-1,-1,-1,-1, 1, 0/
      DATA (NHEL(IHEL,   6),IHEL=1, 6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1, 6) /-1,-1,-1, 0,-1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1, 6) /-1,-1,-1, 0,-1, 0/
      DATA (NHEL(IHEL,   9),IHEL=1, 6) /-1,-1,-1, 0,-1, 1/
      DATA (NHEL(IHEL,  10),IHEL=1, 6) /-1,-1,-1, 0, 1,-1/
      DATA (NHEL(IHEL,  11),IHEL=1, 6) /-1,-1,-1, 0, 1, 0/
      DATA (NHEL(IHEL,  12),IHEL=1, 6) /-1,-1,-1, 0, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1, 6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1, 6) /-1,-1,-1, 1,-1, 0/
      DATA (NHEL(IHEL,  15),IHEL=1, 6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  16),IHEL=1, 6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  17),IHEL=1, 6) /-1,-1,-1, 1, 1, 0/
      DATA (NHEL(IHEL,  18),IHEL=1, 6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  19),IHEL=1, 6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  20),IHEL=1, 6) /-1,-1, 1,-1,-1, 0/
      DATA (NHEL(IHEL,  21),IHEL=1, 6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  22),IHEL=1, 6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  23),IHEL=1, 6) /-1,-1, 1,-1, 1, 0/
      DATA (NHEL(IHEL,  24),IHEL=1, 6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  25),IHEL=1, 6) /-1,-1, 1, 0,-1,-1/
      DATA (NHEL(IHEL,  26),IHEL=1, 6) /-1,-1, 1, 0,-1, 0/
      DATA (NHEL(IHEL,  27),IHEL=1, 6) /-1,-1, 1, 0,-1, 1/
      DATA (NHEL(IHEL,  28),IHEL=1, 6) /-1,-1, 1, 0, 1,-1/
      DATA (NHEL(IHEL,  29),IHEL=1, 6) /-1,-1, 1, 0, 1, 0/
      DATA (NHEL(IHEL,  30),IHEL=1, 6) /-1,-1, 1, 0, 1, 1/
      DATA (NHEL(IHEL,  31),IHEL=1, 6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  32),IHEL=1, 6) /-1,-1, 1, 1,-1, 0/
      DATA (NHEL(IHEL,  33),IHEL=1, 6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  34),IHEL=1, 6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  35),IHEL=1, 6) /-1,-1, 1, 1, 1, 0/
      DATA (NHEL(IHEL,  36),IHEL=1, 6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  37),IHEL=1, 6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  38),IHEL=1, 6) /-1, 1,-1,-1,-1, 0/
      DATA (NHEL(IHEL,  39),IHEL=1, 6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  40),IHEL=1, 6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  41),IHEL=1, 6) /-1, 1,-1,-1, 1, 0/
      DATA (NHEL(IHEL,  42),IHEL=1, 6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  43),IHEL=1, 6) /-1, 1,-1, 0,-1,-1/
      DATA (NHEL(IHEL,  44),IHEL=1, 6) /-1, 1,-1, 0,-1, 0/
      DATA (NHEL(IHEL,  45),IHEL=1, 6) /-1, 1,-1, 0,-1, 1/
      DATA (NHEL(IHEL,  46),IHEL=1, 6) /-1, 1,-1, 0, 1,-1/
      DATA (NHEL(IHEL,  47),IHEL=1, 6) /-1, 1,-1, 0, 1, 0/
      DATA (NHEL(IHEL,  48),IHEL=1, 6) /-1, 1,-1, 0, 1, 1/
      DATA (NHEL(IHEL,  49),IHEL=1, 6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  50),IHEL=1, 6) /-1, 1,-1, 1,-1, 0/
      DATA (NHEL(IHEL,  51),IHEL=1, 6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  52),IHEL=1, 6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  53),IHEL=1, 6) /-1, 1,-1, 1, 1, 0/
      DATA (NHEL(IHEL,  54),IHEL=1, 6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  55),IHEL=1, 6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  56),IHEL=1, 6) /-1, 1, 1,-1,-1, 0/
      DATA (NHEL(IHEL,  57),IHEL=1, 6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  58),IHEL=1, 6) /-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  59),IHEL=1, 6) /-1, 1, 1,-1, 1, 0/
      DATA (NHEL(IHEL,  60),IHEL=1, 6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  61),IHEL=1, 6) /-1, 1, 1, 0,-1,-1/
      DATA (NHEL(IHEL,  62),IHEL=1, 6) /-1, 1, 1, 0,-1, 0/
      DATA (NHEL(IHEL,  63),IHEL=1, 6) /-1, 1, 1, 0,-1, 1/
      DATA (NHEL(IHEL,  64),IHEL=1, 6) /-1, 1, 1, 0, 1,-1/
      DATA (NHEL(IHEL,  65),IHEL=1, 6) /-1, 1, 1, 0, 1, 0/
      DATA (NHEL(IHEL,  66),IHEL=1, 6) /-1, 1, 1, 0, 1, 1/
      DATA (NHEL(IHEL,  67),IHEL=1, 6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  68),IHEL=1, 6) /-1, 1, 1, 1,-1, 0/
      DATA (NHEL(IHEL,  69),IHEL=1, 6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  70),IHEL=1, 6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  71),IHEL=1, 6) /-1, 1, 1, 1, 1, 0/
      DATA (NHEL(IHEL,  72),IHEL=1, 6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  73),IHEL=1, 6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  74),IHEL=1, 6) / 1,-1,-1,-1,-1, 0/
      DATA (NHEL(IHEL,  75),IHEL=1, 6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  76),IHEL=1, 6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  77),IHEL=1, 6) / 1,-1,-1,-1, 1, 0/
      DATA (NHEL(IHEL,  78),IHEL=1, 6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  79),IHEL=1, 6) / 1,-1,-1, 0,-1,-1/
      DATA (NHEL(IHEL,  80),IHEL=1, 6) / 1,-1,-1, 0,-1, 0/
      DATA (NHEL(IHEL,  81),IHEL=1, 6) / 1,-1,-1, 0,-1, 1/
      DATA (NHEL(IHEL,  82),IHEL=1, 6) / 1,-1,-1, 0, 1,-1/
      DATA (NHEL(IHEL,  83),IHEL=1, 6) / 1,-1,-1, 0, 1, 0/
      DATA (NHEL(IHEL,  84),IHEL=1, 6) / 1,-1,-1, 0, 1, 1/
      DATA (NHEL(IHEL,  85),IHEL=1, 6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  86),IHEL=1, 6) / 1,-1,-1, 1,-1, 0/
      DATA (NHEL(IHEL,  87),IHEL=1, 6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  88),IHEL=1, 6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  89),IHEL=1, 6) / 1,-1,-1, 1, 1, 0/
      DATA (NHEL(IHEL,  90),IHEL=1, 6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  91),IHEL=1, 6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  92),IHEL=1, 6) / 1,-1, 1,-1,-1, 0/
      DATA (NHEL(IHEL,  93),IHEL=1, 6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  94),IHEL=1, 6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  95),IHEL=1, 6) / 1,-1, 1,-1, 1, 0/
      DATA (NHEL(IHEL,  96),IHEL=1, 6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  97),IHEL=1, 6) / 1,-1, 1, 0,-1,-1/
      DATA (NHEL(IHEL,  98),IHEL=1, 6) / 1,-1, 1, 0,-1, 0/
      DATA (NHEL(IHEL,  99),IHEL=1, 6) / 1,-1, 1, 0,-1, 1/
      DATA (NHEL(IHEL, 100),IHEL=1, 6) / 1,-1, 1, 0, 1,-1/
      DATA (NHEL(IHEL, 101),IHEL=1, 6) / 1,-1, 1, 0, 1, 0/
      DATA (NHEL(IHEL, 102),IHEL=1, 6) / 1,-1, 1, 0, 1, 1/
      DATA (NHEL(IHEL, 103),IHEL=1, 6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 104),IHEL=1, 6) / 1,-1, 1, 1,-1, 0/
      DATA (NHEL(IHEL, 105),IHEL=1, 6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 106),IHEL=1, 6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 107),IHEL=1, 6) / 1,-1, 1, 1, 1, 0/
      DATA (NHEL(IHEL, 108),IHEL=1, 6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 109),IHEL=1, 6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 110),IHEL=1, 6) / 1, 1,-1,-1,-1, 0/
      DATA (NHEL(IHEL, 111),IHEL=1, 6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 112),IHEL=1, 6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 113),IHEL=1, 6) / 1, 1,-1,-1, 1, 0/
      DATA (NHEL(IHEL, 114),IHEL=1, 6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 115),IHEL=1, 6) / 1, 1,-1, 0,-1,-1/
      DATA (NHEL(IHEL, 116),IHEL=1, 6) / 1, 1,-1, 0,-1, 0/
      DATA (NHEL(IHEL, 117),IHEL=1, 6) / 1, 1,-1, 0,-1, 1/
      DATA (NHEL(IHEL, 118),IHEL=1, 6) / 1, 1,-1, 0, 1,-1/
      DATA (NHEL(IHEL, 119),IHEL=1, 6) / 1, 1,-1, 0, 1, 0/
      DATA (NHEL(IHEL, 120),IHEL=1, 6) / 1, 1,-1, 0, 1, 1/
      DATA (NHEL(IHEL, 121),IHEL=1, 6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 122),IHEL=1, 6) / 1, 1,-1, 1,-1, 0/
      DATA (NHEL(IHEL, 123),IHEL=1, 6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 124),IHEL=1, 6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 125),IHEL=1, 6) / 1, 1,-1, 1, 1, 0/
      DATA (NHEL(IHEL, 126),IHEL=1, 6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 127),IHEL=1, 6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 128),IHEL=1, 6) / 1, 1, 1,-1,-1, 0/
      DATA (NHEL(IHEL, 129),IHEL=1, 6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 130),IHEL=1, 6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 131),IHEL=1, 6) / 1, 1, 1,-1, 1, 0/
      DATA (NHEL(IHEL, 132),IHEL=1, 6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 133),IHEL=1, 6) / 1, 1, 1, 0,-1,-1/
      DATA (NHEL(IHEL, 134),IHEL=1, 6) / 1, 1, 1, 0,-1, 0/
      DATA (NHEL(IHEL, 135),IHEL=1, 6) / 1, 1, 1, 0,-1, 1/
      DATA (NHEL(IHEL, 136),IHEL=1, 6) / 1, 1, 1, 0, 1,-1/
      DATA (NHEL(IHEL, 137),IHEL=1, 6) / 1, 1, 1, 0, 1, 0/
      DATA (NHEL(IHEL, 138),IHEL=1, 6) / 1, 1, 1, 0, 1, 1/
      DATA (NHEL(IHEL, 139),IHEL=1, 6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 140),IHEL=1, 6) / 1, 1, 1, 1,-1, 0/
      DATA (NHEL(IHEL, 141),IHEL=1, 6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 142),IHEL=1, 6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 143),IHEL=1, 6) / 1, 1, 1, 1, 1, 0/
      DATA (NHEL(IHEL, 144),IHEL=1, 6) / 1, 1, 1, 1, 1, 1/
      DATA (  IC(IHEL,   1),IHEL=1, 6) / 1, 2, 3, 4, 5, 6/
      DATA (IDEN(IHEL     ),IHEL=1, 1) / 256/
C --------
C USER SET
C --------
      INTEGER KHEL
      COMMON/HEL/KHEL
      INTEGER HHEL(NEXTERNAL)
      COMMON/HEL2/HHEL
C ----------
C BEGIN CODE
C ----------
      DO IPROC = 1, NCROSS
         CALL SWITCHMOM (P1,P,IC(1,IPROC),JC,NEXTERNAL)
         DO IHEL = 1, NEXTERNAL
            JC(IHEL) = +1
         ENDDO
         ANS(IPROC) = MEGGBWBW (P,NHEL(1,KHEL),JC(1),ICLR)
         DO I = 1,NEXTERNAL
            HHEL(I) = NHEL(I,KHEL)
         ENDDO
         ANS(IPROC) = ANS(IPROC) / DBLE(IDEN(IPROC))
      ENDDO
      END
C
C -------------------------------------------------------------
C
      REAL*8 FUNCTION MEGGBWBW (P,NHEL,IC,ICLR)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C
C FOR PROCESS : g g -> b w+ b~ w-
C
      IMPLICIT NONE
C
C CONSTANTS
C
      INTEGER    NGRAPHS,    NEIGEN
      PARAMETER (NGRAPHS=   15,NEIGEN=  2)
      include "genps.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=  30, NCOLOR=   2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C
C ARGUMENTS
C
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL),IC(NEXTERNAL)
C
C LOCAL VARIABLES
C
      INTEGER I,J,ICLR
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR),CF(NCOLOR,NCOLOR)
      REAL*8 CF1(NCOLOR,NCOLOR),CF8(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS),JAMP(NCOLOR),RAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS)
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_g/  amp2,       jamp2
      include "coupl_sm.inc"
C ----------
C     COLOR DATA
C ----------
      DATA Denom(1  )/            3/
      DATA Denom(2  )/            3/
      DATA (CF(i,1  ),i=1  ,2  ) /    16,   -2/
C     T[ 3, 5, 2, 1]
      DATA (CF(i,2  ),i=1  ,2  ) /    -2,   16/
C     T[ 3, 5, 1, 2]
C
      DATA (CF1(i,1  ),i=1  ,2 ) /     2,    2/
      DATA (CF1(i,2  ),i=1  ,2 ) /     2,    2/
      DATA (CF8(i,1  ),i=1  ,2 ) /    14,   -4/
      DATA (CF8(i,2  ),i=1  ,2 ) /    -4,   14/
C --------
C USER SET
C --------
      COMPLEX*16 TP(6),TB(6)
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      COMPLEX*16 AMPT,AMPU,AMPS,OV1,OV2
      include 'thr.inc'
      include "kin_functions.inc"
      DOUBLE PRECISION RTC(NCOLOR)
      COMMON/COL/RTC
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX(P(0,1   ),ZERO  ,NHEL(1   ),-1*IC(1   ),W(1,1   ))        
      CALL VXXXXX(P(0,2   ),ZERO  ,NHEL(2   ),-1*IC(2   ),W(1,2   ))        
      CALL OXXXXX(P(0,3   ),BMASS ,NHEL(3   ),+1*IC(3   ),W(1,3   ))       
      CALL VXXXXX(P(0,4   ),WMASS ,NHEL(4   ),+1*IC(4   ),W(1,4   ))       
      CALL IXXXXX(P(0,5   ),BMASS ,NHEL(5   ),-1*IC(5   ),W(1,5   ))       
      CALL VXXXXX(P(0,6   ),WMASS ,NHEL(6   ),+1*IC(6   ),W(1,6   ))       
      CALL FVOXXX(W(1,3),W(1,4), GWF, TMASS, TWIDTH, TP) ! t = bW+
      CALL FVIXXX(W(1,5),W(1,6), GWF, TMASS, TWIDTH, TB) ! t~ = b~W-
      MT1S = SumDot(P(0,3),P(0,4),+1D0)
      MT2S = SumDot(P(0,5),P(0,6),+1D0)
      S    = SumDot(P(0,1),P(0,2),+1D0)
C...  Resonant Amplitudes
      DO I = 1, NGRAPHS
         AMP(I) = (0D0,0D0)
      ENDDO
      CALL GGTTRES (W(1,1),W(1,2),TP,TB,AMPT,AMPU,AMPS,ICLR)
      AMP(10) = AMPT
      AMP( 7) = AMPU
      AMP(14) = AMPS
      IF (INR.EQ.0) GOTO 100
C...  Non-Resonant Amplitudes
      CALL FVOXXX(W(1,3   ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,7   ))     
      CALL FVOXXX(W(1,7   ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,8   ))    
      CALL FVOXXX(W(1,8   ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,9   ))     
      CALL IOVXXX(W(1,5   ),W(1,9   ),W(1,6   ),GWF ,AMP(1   ))            
      CALL FVIXXX(W(1,5   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,10  ))     
      CALL IOVXXX(W(1,10  ),W(1,8   ),W(1,6   ),GWF ,AMP(2   ))            
      CALL FVOXXX(W(1,7   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,11  ))     
      CALL FVOXXX(W(1,11  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,12  ))    
      CALL IOVXXX(W(1,5   ),W(1,12  ),W(1,6   ),GWF ,AMP(3   ))            
      CALL FVOXXX(W(1,3   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,13  ))     
      CALL FVOXXX(W(1,13  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,14  ))    
      CALL FVOXXX(W(1,14  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,15  ))     
      CALL IOVXXX(W(1,5   ),W(1,15  ),W(1,6   ),GWF ,AMP(4   ))            
      CALL FVIXXX(W(1,5   ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,16  ))     
      CALL IOVXXX(W(1,16  ),W(1,14  ),W(1,6   ),GWF ,AMP(5   ))            
      CALL FVOXXX(W(1,13  ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,17  ))     
      CALL FVOXXX(W(1,17  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,18  ))    
      CALL IOVXXX(W(1,5   ),W(1,18  ),W(1,6   ),GWF ,AMP(6   ))            
      CALL FVOXXX(W(1,3   ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,19  ))    
      CALL FVOXXX(W(1,19  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,20  ))     
*     CALL FVOXXX(W(1,20  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,21  ))     
*     CALL IOVXXX(W(1,5   ),W(1,21  ),W(1,6   ),GWF ,AMP(7   ))            
      CALL FVIXXX(W(1,10  ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,22  ))     
      CALL IOVXXX(W(1,22  ),W(1,19  ),W(1,6   ),GWF ,AMP(8   ))            
      CALL IOVXXX(W(1,10  ),W(1,20  ),W(1,6   ),GWF ,AMP(9   ))            
      CALL FVOXXX(W(1,19  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,23  ))     
*     CALL FVOXXX(W(1,23  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,24  ))     
*     CALL IOVXXX(W(1,5   ),W(1,24  ),W(1,6   ),GWF ,AMP(10  ))            
      CALL FVIXXX(W(1,16  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,25  ))     
      CALL IOVXXX(W(1,25  ),W(1,19  ),W(1,6   ),GWF ,AMP(11  ))            
      CALL IOVXXX(W(1,16  ),W(1,23  ),W(1,6   ),GWF ,AMP(12  ))            
      CALL JVVXXX(W(1,1   ),W(1,2   ),G ,ZERO    ,ZERO    ,W(1,26  ))      
      CALL FVOXXX(W(1,3   ),W(1,26  ),GG ,BMASS   ,ZERO    ,W(1,27  ))     
      CALL FVOXXX(W(1,27  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,28  ))    
      CALL IOVXXX(W(1,5   ),W(1,28  ),W(1,6   ),GWF ,AMP(13  ))            
*     CALL FVOXXX(W(1,19  ),W(1,26  ),GG ,TMASS   ,TWIDTH  ,W(1,29  ))     
*     CALL IOVXXX(W(1,5   ),W(1,29  ),W(1,6   ),GWF ,AMP(14  ))            
      CALL FVIXXX(W(1,5   ),W(1,26  ),GG ,BMASS   ,ZERO    ,W(1,30  ))     
      CALL IOVXXX(W(1,30  ),W(1,19  ),W(1,6   ),GWF ,AMP(15  ))            
C.....
      IF (INR.EQ.2) THEN        ! OFS
         OV1 = DCMPLX(MT1S-TMASS**2,0D0 ) /
     -        DCMPLX( MT1S-TMASS**2,TMASS*TWIDTH)
         OV2 = DCMPLX(MT2S-TMASS**2,0D0 ) /
     -        DCMPLX( MT2S-TMASS**2,TMASS*TWIDTH)
         AMP( 1) = AMP( 1) * OV1*OV2
         AMP( 2) = AMP( 2) * OV1*OV2
         AMP( 3) = AMP( 3) * OV1*OV2
         AMP( 4) = AMP( 4) * OV1*OV2
         AMP( 5) = AMP( 5) * OV1*OV2
         AMP( 6) = AMP( 6) * OV1*OV2
         AMP( 8) = AMP( 8) * OV1*OV2
         AMP( 9) = AMP( 9) * OV1*OV2
         AMP(11) = AMP(11) * OV1*OV2
         AMP(12) = AMP(12) * OV1*OV2
         AMP(13) = AMP(13) * OV1*OV2
         AMP(15) = AMP(15) * OV1*OV2
      ENDIF
C.....
 100  CONTINUE
      JAMP(1) = AMP(   1)+AMP(   2)+AMP(   3)+AMP(   7)+AMP(   8)
     &     +AMP(   9)-AMP(  13)-AMP(  14)-AMP(  15)
      JAMP(2) = AMP(   4)+AMP(   5)+AMP(   6)+AMP(  10)+AMP(  11)
     &     +AMP(  12)+AMP(  13)+AMP(  14)+AMP(  15)
      MEGGBWBW = 0D0
      DO I = 1, NCOLOR
         ZTEMP = DCMPLX (0D0,0D0)
         DO J = 1, NCOLOR
            IF (ICLR.EQ.0) THEN
               ZTEMP = ZTEMP + CF(J,I) * JAMP(J)
            ELSEIF (ICLR.EQ.1) THEN
               ZTEMP = ZTEMP + CF1(J,I) * JAMP(J)
            ELSEIF (ICLR.EQ.2) THEN
               ZTEMP = ZTEMP + CF8(J,I) * JAMP(J)
            ENDIF
         ENDDO
         MEGGBWBW = MEGGBWBW + DBLE( ZTEMP*DCONJG(JAMP(I)) ) / DENOM(I)
      ENDDO
      Do I = 1, NCOLOR
         Jamp2(i)=Jamp2(i)+Jamp(i)*dconjg(Jamp(i))
      Enddo
      DO I = 1,NCOLOR
         RTC(I) = jamp2(I) / (jamp2(1)+jamp2(2))
      ENDDO
      END
