      SUBROUTINE QQBWBLV (P1,ANS)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C
C FOR PROCESS : u u~ -> b w+ b~ mu- vm~
C
C Crossing   1 is u u~ -> b w+ b~ mu- vm~
      IMPLICIT NONE
C
C CONSTANTS
C
      Include "genps.inc"
      INTEGER    NCOMB,    NCROSS
      PARAMETER (NCOMB=24, NCROSS=1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C
C ARGUMENTS
C
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C
C LOCAL VARIABLES
C
      INTEGER NHEL(NEXTERNAL,NCOMB), NTRY
      REAL*8 T, P(0:3,NEXTERNAL)
      REAL*8 MEQQBWBLV
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL), I
      INTEGER NGRAPHS
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_q/  amp2,       jamp2
      DATA NGRAPHS /1/
      DATA jamp2(0) /1/
      DATA (NHEL(IHEL,  1),IHEL=1, 7) /-1, 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  2),IHEL=1, 7) /-1, 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  3),IHEL=1, 7) /-1, 1,-1, 0,-1,-1, 1/
      DATA (NHEL(IHEL,  4),IHEL=1, 7) /-1, 1,-1, 0, 1,-1, 1/
      DATA (NHEL(IHEL,  5),IHEL=1, 7) /-1, 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  6),IHEL=1, 7) /-1, 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  7),IHEL=1, 7) /-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  8),IHEL=1, 7) /-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  9),IHEL=1, 7) /-1, 1, 1, 0,-1,-1, 1/
      DATA (NHEL(IHEL, 10),IHEL=1, 7) /-1, 1, 1, 0, 1,-1, 1/
      DATA (NHEL(IHEL, 11),IHEL=1, 7) /-1, 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 12),IHEL=1, 7) /-1, 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 13),IHEL=1, 7) / 1,-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 14),IHEL=1, 7) / 1,-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 15),IHEL=1, 7) / 1,-1,-1, 0,-1,-1, 1/
      DATA (NHEL(IHEL, 16),IHEL=1, 7) / 1,-1,-1, 0, 1,-1, 1/
      DATA (NHEL(IHEL, 17),IHEL=1, 7) / 1,-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 18),IHEL=1, 7) / 1,-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 19),IHEL=1, 7) / 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 20),IHEL=1, 7) / 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 21),IHEL=1, 7) / 1,-1, 1, 0,-1,-1, 1/
      DATA (NHEL(IHEL, 22),IHEL=1, 7) / 1,-1, 1, 0, 1,-1, 1/
      DATA (NHEL(IHEL, 23),IHEL=1, 7) / 1,-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 24),IHEL=1, 7) / 1,-1, 1, 1, 1,-1, 1/
      DATA (  IC(IHEL,  1),IHEL=1, 7) / 1, 2, 3, 4, 5, 6, 7/
      DATA (IDEN(IHEL),IHEL=  1,  1) /  36/
C ----------
C BEGIN CODE
C ----------
      DO IPROC = 1, NCROSS
         CALL SWITCHMOM (P1,P,IC(1,IPROC),JC,NEXTERNAL)
         DO IHEL = 1, NEXTERNAL
            JC(IHEL) = +1
         ENDDO
         ANS(IPROC) = 0D0
         DO IHEL = 1, NCOMB
            T = MEQQBWBLV (P,NHEL(1,IHEL),JC(1))
            ANS(IPROC) = ANS(IPROC) + T
         ENDDO
         ANS(IPROC) = ANS(IPROC) / DBLE(IDEN(IPROC))
      ENDDO
      END
C
C
      REAL*8 FUNCTION MEQQBWBLV (P,NHEL,IC)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C
C FOR PROCESS : u u~ -> b w+ b~ mu- vm~
C
      IMPLICIT NONE
C
C CONSTANTS
C
      INTEGER    NGRAPHS,    NEIGEN
      PARAMETER (NGRAPHS=   1,NEIGEN=  1)
      include "genps.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=   16, NCOLOR=   1)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C
C ARGUMENTS
C
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C
C LOCAL VARIABLES
C
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS)
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps_q/  amp2,       jamp2
      include "coupl_sm.inc"
C
C COLOR DATA
C
      DATA Denom(1  )/            1/
      DATA (CF(i,1  ),i=1  ,1  ) /     2/
C     T[ 3, 1]T[ 2, 6]
C
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      DOUBLE PRECISION PW(0:3)
      DOUBLE COMPLEX GAMMA
      include 'thr.inc'
      include 'kin_functions.inc'
C ----------
C BEGIN CODE
C ----------
      CALL IXXXXX (P(0,1),ZERO  ,NHEL(1),+1*IC(1),W(1, 1)) ! q
      CALL OXXXXX (P(0,2),ZERO  ,NHEL(2),-1*IC(2),W(1, 2)) ! q~
      CALL OXXXXX (P(0,3),BMASS ,NHEL(3),+1*IC(3),W(1, 3)) ! b
      CALL VXXXXX (P(0,4),WMASS ,NHEL(4),+1*IC(4),W(1, 4)) ! W+
      CALL IXXXXX (P(0,5),BMASS ,NHEL(5),-1*IC(5),W(1, 5)) ! b~
      CALL OXXXXX (P(0,6),ZERO  ,NHEL(6),+1*IC(6),W(1, 6)) ! mu-
      CALL IXXXXX (P(0,7),ZERO  ,NHEL(7),-1*IC(7),W(1, 7)) ! vm~
      CALL JIOXXX (W(1,7),W(1,6),GWF,WMASS,WWIDTH,W(1, 8)) ! W-*
      CALL FVOXXX (W(1,3),W(1,4),GWF,TMASS,TWIDTH,W(1, 9)) ! t*
      CALL FVIXXX (W(1,5),W(1,8),GWF,TMASS,TWIDTH,W(1,10)) ! t~*
      DO I = 0, 3
         PW(I) = P(I,6) + P(I,7)
      ENDDO
      MT1S = SumDot(P(0,3),P(0,4),+1D0)
      MT2S = SumDot(P(0,5),PW( 0),+1D0)
      S    = SumDot(P(0,1),P(0,2),+1D0)
C...
*      CALL IXXXXX (P(0,1),ZERO  ,NHEL(1),+1*IC(1),W(1, 1)) ! q
*      CALL OXXXXX (P(0,2),ZERO  ,NHEL(2),-1*IC(2),W(1, 2)) ! q~
*      CALL IXXXXX (P(0,3),BMASS ,NHEL(3),-1*IC(3),W(1, 3)) ! b~
*      CALL VXXXXX (P(0,4),WMASS ,NHEL(4),+1*IC(4),W(1, 4)) ! W-
*      CALL OXXXXX (P(0,5),BMASS ,NHEL(5),+1*IC(5),W(1, 5)) ! b
*      CALL IXXXXX (P(0,6),ZERO  ,NHEL(6),-1*IC(6),W(1, 6)) ! mu+
*      CALL OXXXXX (P(0,7),ZERO  ,NHEL(7),+1*IC(7),W(1, 7)) ! vm
*      CALL JIOXXX (W(1,6),W(1,7),GWF,WMASS,WWIDTH,W(1, 8)) ! W+*
*      CALL FVOXXX (W(1,5),W(1,8),GWF,TMASS,TWIDTH,W(1, 9)) ! t*
*      CALL FVIXXX (W(1,3),W(1,4),GWF,TMASS,TWIDTH,W(1,10)) ! t~*
C...  Resonant diagram
      CALL JIOXXX (W(1,1),W(1,2),GG,ZERO,ZERO,W(1,11)) ! g*
      CALL IOVXXX (W(1,10),W(1,9),W(1,11),GG,AMP(1))
      IF (IGRN.GE.1) THEN
         CALL GRNMOD (GAMMA,MT1S,MT2S,S,TMASS,2,IGRN)
         AMP(1) = AMP(1) * GAMMA
      ENDIF
      JAMP(1) = -AMP(1)
      MEQQBWBLV = 0D0
      DO I = 1, NCOLOR
         ZTEMP = (0D0,0D0)
         DO J = 1, NCOLOR
            ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
         ENDDO
         MEQQBWBLV = MEQQBWBLV + ZTEMP*DCONJG(JAMP(I))/DENOM(I)
      ENDDO
      END
