      LOGICAL ICOLAMP(  39,   2)
      DATA ICOLAMP/.true.,.true.,.true.,.true.,.false.,.false.,
     &             .false.,.false.,.false.,.false.,.false.,.false.,
     &             .false.,.false.,.false.,.true.,.true.,.true.,
     &             .true.,.true.,.true.,.true.,.true.,.false.,
     &             .true.,.true.,.true.,.true.,.true.,.false.,
     &             .false.,.false.,.true.,.true.,.true.,.true.,
     &             .true.,.true.,.true.,.false.,.false.,.false.,
     &             .false.,.true.,.true.,.true.,.true.,.true.,
     &             .true.,.true.,.true.,.true.,.true.,.true.,.false.,
     &             .false.,.false.,.false.,.false.,.false.,.false.,
     &             .false.,.true.,.true.,.true.,.false.,.false.,
     &             .false.,.true.,.true.,.true.,.true.,.true.,
     &             .true.,.true.,.true.,.true.,.true./