      SUBROUTINE GGBLVBLV (P1,ANS,ICLR)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C
C FOR PROCESS : g g -> b mu+ vm b~ mu- vm~
C
C Crossing   1 is g g -> b mu+ vm b~ mu- vm~
      IMPLICIT NONE
C
C CONSTANTS
C
      Include "genps.inc"
      INTEGER    NCOMB,    NCROSS
      PARAMETER (NCOMB=16, NCROSS=1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C
C ARGUMENTS
C
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C
C LOCAL VARIABLES
C
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T, P(0:3,NEXTERNAL)
      REAL*8 MEGGBLVBLV
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL), I, ICLR
      INTEGER NGRAPHS
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps/  amp2,       jamp2
      DATA NGRAPHS /    3/
      DATA jamp2(0) /   2/
      DATA (NHEL(IHEL,  1),IHEL=1, 8) /-1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  2),IHEL=1, 8) /-1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  3),IHEL=1, 8) /-1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  4),IHEL=1, 8) /-1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  5),IHEL=1, 8) /-1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  6),IHEL=1, 8) /-1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  7),IHEL=1, 8) /-1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  8),IHEL=1, 8) /-1, 1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  9),IHEL=1, 8) / 1,-1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 10),IHEL=1, 8) / 1,-1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 11),IHEL=1, 8) / 1,-1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 12),IHEL=1, 8) / 1,-1, 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 13),IHEL=1, 8) / 1, 1,-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 14),IHEL=1, 8) / 1, 1,-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 15),IHEL=1, 8) / 1, 1, 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 16),IHEL=1, 8) / 1, 1, 1, 1,-1, 1,-1, 1/
      DATA (  IC(IHEL,  1),IHEL=1, 8) / 1, 2, 3, 4, 5, 6, 7, 8/
      DATA (IDEN(IHEL),IHEL=  1,  1) / 256/
C ----------
C BEGIN CODE
C ----------
      DO IPROC = 1, NCROSS
         CALL SWITCHMOM (P1,P,IC(1,IPROC),JC,NEXTERNAL)
         DO IHEL = 1, NEXTERNAL
            JC(IHEL) = +1
         ENDDO
         ANS(IPROC) = 0D0
         DO IHEL = 1, NCOMB
            T = MEGGBLVBLV (P,NHEL(1,IHEL),JC(1),ICLR)
            ANS(IPROC) = ANS(IPROC) + T
         ENDDO
         ANS(IPROC) = ANS(IPROC) / DBLE(IDEN(IPROC))
      ENDDO
      END
C
C
      REAL*8 FUNCTION MEGGBLVBLV (P,NHEL,IC,ICLR)
C
C Generated by MadGraph II
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C
C FOR PROCESS : g g -> b mu+ vm b~ mu- vm~
C
      IMPLICIT NONE
C
C CONSTANTS
C
      INTEGER    NGRAPHS,    NEIGEN
      PARAMETER (NGRAPHS=3, NEIGEN=  2)
      include "genps.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=  15, NCOLOR=   2)
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C
C ARGUMENTS
C
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C
C LOCAL VARIABLES
C
      INTEGER I,J,ICLR
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      REAL*8 CF1(NCOLOR,NCOLOR), CF8(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS)
C
C GLOBAL VARIABLES
C
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps/  amp2,       jamp2
      include "coupl_sm.inc"
C
C ----------
C COLOR DATA
C ----------
      DATA Denom(1  )/            3/
      DATA Denom(2  )/            3/
      DATA (CF(i,1  ),i=1  ,2  ) /    16,   -2/
C     T[ 3, 5, 2, 1]
      DATA (CF(i,2  ),i=1  ,2  ) /    -2,   16/
C     T[ 3, 5, 1, 2]
      DATA (CF1(i,1  ),i=1  ,2 ) /     2,    2/
      DATA (CF1(i,2  ),i=1  ,2 ) /     2,    2/
      DATA (CF8(i,1  ),i=1  ,2 ) /    14,   -4/
      DATA (CF8(i,2  ),i=1  ,2 ) /    -4,   14/
C --------
C USER SET
C --------
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      DOUBLE PRECISION PW1(0:3),PW2(0:3)
      include 'thr.inc'
      include "kin_functions.inc"
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX (P(0, 1),ZERO   ,NHEL(1),-1*IC(1),W(1, 1)) ! g1
      CALL VXXXXX (P(0, 2),ZERO   ,NHEL(2),-1*IC(2),W(1, 2)) ! g2
      CALL OXXXXX (P(0, 3),BMASS  ,NHEL(3),+1*IC(3),W(1, 3)) ! b
      CALL IXXXXX (P(0, 4),ZERO   ,NHEL(4),-1*IC(4),W(1, 4)) ! mu+
      CALL OXXXXX (P(0, 5),ZERO   ,NHEL(5),+1*IC(5),W(1, 5)) ! vm
      CALL IXXXXX (P(0, 6),BMASS  ,NHEL(6),-1*IC(6),W(1, 6)) ! b~
      CALL OXXXXX (P(0, 7),ZERO   ,NHEL(7),+1*IC(7),W(1, 7)) ! mu-
      CALL IXXXXX (P(0, 8),ZERO   ,NHEL(8),-1*IC(8),W(1, 8)) ! vm~
      CALL JIOXXX (W(1, 4),W(1, 5),GWF,WMASS,WWIDTH,W(1, 9)) ! W+*
      CALL JIOXXX (W(1, 8),W(1, 7),GWF,WMASS,WWIDTH,W(1,10)) ! W-*
      CALL FVOXXX (W(1, 3),W(1, 9),GWF,TMASS,TWIDTH,W(1,11)) ! t*
      CALL FVIXXX (W(1, 6),W(1,10),GWF,TMASS,TWIDTH,W(1,12)) ! t~*
      DO I = 0, 3
         PW1(I) = P(I,4) + P(I,5)
         PW2(I) = P(I,7) + P(I,8)
      ENDDO
      MT1S = SumDot(P(0,3),PW1(0),+1D0)
      MT2S = SumDot(P(0,6),PW2(0),+1D0)
      S    = SumDot(P(0,1),P(0,2),+1D0)
C...  Resonant Amplitudes
      CALL GGTTRES (W(1,1),W(1,2),W(1,11),W(1,12),AMP(1),AMP(2),AMP(3)
     -     ,ICLR)
      JAMP(1) = AMP(1) + AMP(3)
      JAMP(2) = AMP(2) - AMP(3)
      MEGGBLVBLV = 0D0
      DO I = 1, NCOLOR
         ZTEMP = DCMPLX (0D0,0D0)
         DO J = 1, NCOLOR
            IF (ICLR.EQ.0) THEN
               ZTEMP = ZTEMP + CF (J,I) * JAMP(J)
            ELSEIF (ICLR.EQ.1) THEN
               ZTEMP = ZTEMP + CF1(J,I) * JAMP(J)
            ELSEIF (ICLR.EQ.2) THEN
               ZTEMP = ZTEMP + CF8(J,I) * JAMP(J)
            ENDIF
         ENDDO
         MEGGBLVBLV = MEGGBLVBLV + DBLE(ZTEMP*DCONJG(JAMP(I)))/DENOM(I)
      ENDDO
      END
