C...  NO : 0:LO, 1:NLO, 2:NNLO, 3:NNNLO
C...  AS BY PEGASUS ... AS = ALHPAS/(4.*PI)
C...  Use of asrgtk.f and betafct.f
      DOUBLE PRECISION FUNCTION ALPHAS (MU,MU0,AS0,NF,NO)
      IMPLICIT NONE
      DOUBLE PRECISION AS0,ASF,MU0,MU
      INTEGER NF,NO
      DOUBLE PRECISION PI
      PARAMETER (PI=3.141592654D0)
      DOUBLE PRECISION AS
      EXTERNAL AS
      DOUBLE PRECISION CF,CA,TR
      COMMON/COLOUR/CF,CA,TR
      DATA CF,CA,TR/1.333333333333D0,3D0,0.5D0/
      INTEGER NAORD, NASTPS
      COMMON/ASPAR/NAORD,NASTPS
      DATA NASTPS/20/
      NAORD = NO
      CALL BETAFCT
      ASF = AS (MU**2,MU0**2,AS0/(4.*PI),NF)
      ALPHAS = ASF * (4.*PI)
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION ASQCD (MU,INF)
      IMPLICIT NONE
      DOUBLE PRECISION MU,MU0,AS0
      INTEGER INF
      DOUBLE PRECISION ALPHAS
      EXTERNAL ALPHAS
      PARAMETER (MU0=91.2D0,AS0=0.118D0)
      ASQCD = ALPHAS (MU,MU0,AS0,INF,1)
      RETURN
      END
*
*      PROGRAM MAIN
*      IMPLICIT NONE
*      DOUBLE PRECISION AS0,ASF,MU0,MUS0,MU,MUS
*      INTEGER NF,NORD
*      DOUBLE PRECISION ALPHAS
*      EXTERNAL ALPHAS
*C
*      NORD = 1                  ! 0:LO, 1:NLO, 2:NNLO, 3:NNNLO
*      NF = 5                    ! Number of Flavor
*C
*      MU0  = 91.1876D0
*      AS0  = 0.12D0
*C
*      MU = 20D0
*      ASF = ALPHAS (MU,MU0,AS0,NF,NORD)
*      WRITE (6,*) MU, ASF, NF, NORD
* 100  CONTINUE
*C
*      STOP
*      END
