      PROGRAM TEST
      IMPLICIT NONE
      INTEGER I,IE,IP,ICLR
      DOUBLE PRECISION E,P
      DOUBLE COMPLEX GAMMA,GRN
      DOUBLE PRECISION PI
      DOUBLE COMPLEX CIMG
      PARAMETER (PI=3.141592654D0,CIMG=(0D0,1D0))
      INTEGER EINT,PINT
      DOUBLE PRECISION EE,PP
      DOUBLE PRECISION MT,GAMT,ASB
      COMMON/GrnPAR/MT,GAMT,ASB
      include "tblgrnep.inc"
C.....
      ICLR = 1
C.....
      CALL READHEAD (ICLR)
C.....
      E = 0D0
C.....
      PMIN = 56D0
      PMAX = 78D0
C.....
      DO 100 P = PMIN, PMAX, .1D0
*      DO 100 IP = 0,NP
*         P = PP(IP,IT)
         CALL READGRN (GAMMA,E,P,ICLR)
         GRN = -GAMMA / (E+CIMG*GAMT-P**2/MT)
         WRITE (7,*) P, ABS(GAMMA)**2, DREAL(GAMMA), DIMAG(GAMMA)
         WRITE (8,*) P, ABS(GRN)**2,   DREAL(GRN),   DIMAG(GRN)
         WRITE (9,*) P, 4D0*PI*P**2*ABS(GRN)**2
         CALL READGRNTBL (GAMMA,EINT(E,IT),PINT(P,IT),ICLR,IT)
         WRITE (17,*) PP(PINT(P,IT),IT),DBLE(GAMMA*DCONJG(GAMMA)),GAMMA
 100  CONTINUE
      STOP
      END
