c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   1) /      24/
      data(iforest(i, -2,   1),i=1,2) /  8,  7/          !  ZERO    ZERO    
      data sprop(  -2,   1) /      21/
      data(iforest(i, -3,   1),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   1) /     -24/
      data(iforest(i, -4,   1),i=1,2) /  1, -2/          !  ZERO    ZERO    
      data tprid(  -4,   1) /       1/
      data(iforest(i, -5,   1),i=1,2) / -4, -3/          !  ZERO    ZERO    
      data tprid(  -5,   1) /      -2/
      data(iforest(i, -6,   1),i=1,2) / -5, -1/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   2) /      24/
      data(iforest(i, -2,   2),i=1,2) /  8,  7/          !  ZERO    ZERO    
      data sprop(  -2,   2) /      21/
      data(iforest(i, -3,   2),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   2) /     -24/
      data(iforest(i, -4,   2),i=1,2) /  1, -3/          !  ZERO    ZERO    
      data tprid(  -4,   2) /      -2/
      data(iforest(i, -5,   2),i=1,2) / -4, -1/          !  ZERO    ZERO    
      data tprid(  -5,   2) /      -1/
      data(iforest(i, -6,   2),i=1,2) / -5, -2/          !  
c   Graph      3
      data mapconfig(   3) /   3/
      data(iforest(i, -1,   3),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   3) /      24/
      data(iforest(i, -2,   3),i=1,2) /  8,  7/          !  ZERO    ZERO    
      data sprop(  -2,   3) /      21/
      data(iforest(i, -3,   3),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   3) /     -24/
      data(iforest(i, -4,   3),i=1,2) /  1, -3/          !  ZERO    ZERO    
      data tprid(  -4,   3) /      -2/
      data(iforest(i, -5,   3),i=1,2) / -4, -2/          !  ZERO    ZERO    
      data tprid(  -5,   3) /      -2/
      data(iforest(i, -6,   3),i=1,2) / -5, -1/          !  
c   Graph      4
      data mapconfig(   4) /   4/
      data(iforest(i, -1,   4),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   4) /      24/
      data(iforest(i, -2,   4),i=1,2) /  8,  7/          !  ZERO    ZERO    
      data sprop(  -2,   4) /      21/
      data(iforest(i, -3,   4),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   4) /     -24/
      data(iforest(i, -4,   4),i=1,2) / -3, -1/          !  ZERO    AWIDTH  
      data sprop(  -4,   4) /      22/
      data(iforest(i, -5,   4),i=1,2) /  1, -2/          !  ZERO    ZERO    
      data tprid(  -5,   4) /       1/
      data(iforest(i, -6,   4),i=1,2) / -5, -4/          !  
c   Graph      5
      data mapconfig(   5) /   5/
      data(iforest(i, -1,   5),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   5) /      24/
      data(iforest(i, -2,   5),i=1,2) /  8,  7/          !  ZERO    ZERO    
      data sprop(  -2,   5) /      21/
      data(iforest(i, -3,   5),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   5) /     -24/
      data(iforest(i, -4,   5),i=1,2) / -3, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -4,   5) /      23/
      data(iforest(i, -5,   5),i=1,2) /  1, -2/          !  ZERO    ZERO    
      data tprid(  -5,   5) /       1/
      data(iforest(i, -6,   5),i=1,2) / -5, -4/          !  
c   Graph      6
      data mapconfig(   6) /   6/
      data(iforest(i, -1,   6),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   6) /      24/
      data(iforest(i, -2,   6),i=1,2) /  8,  7/          !  ZERO    ZERO    
      data sprop(  -2,   6) /      21/
      data(iforest(i, -3,   6),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   6) /     -24/
      data(iforest(i, -4,   6),i=1,2) / -3, -1/          !  ZERO    AWIDTH  
      data sprop(  -4,   6) /      22/
      data(iforest(i, -5,   6),i=1,2) /  1, -4/          !  ZERO    ZERO    
      data tprid(  -5,   6) /      -1/
      data(iforest(i, -6,   6),i=1,2) / -5, -2/          !  
c   Graph      7
      data mapconfig(   7) /   7/
      data(iforest(i, -1,   7),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   7) /      24/
      data(iforest(i, -2,   7),i=1,2) /  8,  7/          !  ZERO    ZERO    
      data sprop(  -2,   7) /      21/
      data(iforest(i, -3,   7),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   7) /     -24/
      data(iforest(i, -4,   7),i=1,2) / -3, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -4,   7) /      23/
      data(iforest(i, -5,   7),i=1,2) /  1, -4/          !  ZERO    ZERO    
      data tprid(  -5,   7) /      -1/
      data(iforest(i, -6,   7),i=1,2) / -5, -2/          !  
c   Graph      8
      data mapconfig(   8) /   8/
      data(iforest(i, -1,   8),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   8) /      24/
      data(iforest(i, -2,   8),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,   8) /       6/
      data(iforest(i, -3,   8),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   8) /     -24/
      data(iforest(i, -4,   8),i=1,2) / -3, -2/          !  BMASS   ZERO    
      data sprop(  -4,   8) /       5/
      data(iforest(i, -5,   8),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,   8) /      21/
c   Graph      9
      data mapconfig(   9) /   9/
      data(iforest(i, -1,   9),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   9) /      24/
      data(iforest(i, -2,   9),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,   9) /       6/
      data(iforest(i, -3,   9),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   9) /     -24/
      data(iforest(i, -4,   9),i=1,2) /  8, -3/          !  TMASS   TWIDTH  
      data sprop(  -4,   9) /      -6/
      data(iforest(i, -5,   9),i=1,2) / -4, -2/          !  ZERO    ZERO    
      data sprop(  -5,   9) /      21/
c   Graph     10
      data mapconfig(  10) /  10/
      data(iforest(i, -1,  10),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  10) /      24/
      data(iforest(i, -2,  10),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  10) /     -24/
      data(iforest(i, -3,  10),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  10) /      22/
      data(iforest(i, -4,  10),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  10) /       5/
      data(iforest(i, -5,  10),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,  10) /      21/
c   Graph     11
      data mapconfig(  11) /  11/
      data(iforest(i, -1,  11),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  11) /      24/
      data(iforest(i, -2,  11),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  11) /     -24/
      data(iforest(i, -3,  11),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  11) /      23/
      data(iforest(i, -4,  11),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  11) /       5/
      data(iforest(i, -5,  11),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,  11) /      21/
c   Graph     12
      data mapconfig(  12) /  12/
      data(iforest(i, -1,  12),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  12) /      24/
      data(iforest(i, -2,  12),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  12) /     -24/
      data(iforest(i, -3,  12),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  12) /      25/
      data(iforest(i, -4,  12),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  12) /       5/
      data(iforest(i, -5,  12),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,  12) /      21/
c   Graph     13
      data mapconfig(  13) /  13/
      data(iforest(i, -1,  13),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  13) /      24/
      data(iforest(i, -2,  13),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  13) /     -24/
      data(iforest(i, -3,  13),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data sprop(  -3,  13) /      -6/
      data(iforest(i, -4,  13),i=1,2) / -3, -1/          !  BMASS   ZERO    
      data sprop(  -4,  13) /      -5/
      data(iforest(i, -5,  13),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  13) /      21/
c   Graph     14
      data mapconfig(  14) /  14/
      data(iforest(i, -1,  14),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  14) /      24/
      data(iforest(i, -2,  14),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  14) /     -24/
      data(iforest(i, -3,  14),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  14) /      22/
      data(iforest(i, -4,  14),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  14) /      -5/
      data(iforest(i, -5,  14),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  14) /      21/
c   Graph     15
      data mapconfig(  15) /  15/
      data(iforest(i, -1,  15),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  15) /      24/
      data(iforest(i, -2,  15),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  15) /     -24/
      data(iforest(i, -3,  15),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  15) /      23/
      data(iforest(i, -4,  15),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  15) /      -5/
      data(iforest(i, -5,  15),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  15) /      21/
c   Graph     16
      data mapconfig(  16) /  16/
      data(iforest(i, -1,  16),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  16) /      24/
      data(iforest(i, -2,  16),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  16) /     -24/
      data(iforest(i, -3,  16),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  16) /      25/
      data(iforest(i, -4,  16),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  16) /      -5/
      data(iforest(i, -5,  16),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  16) /      21/
      data mapconfig(   0) /  16/
