c   Graph      1
      data mapconfig(   1) /   1/
      data(iforest(i, -1,   1),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   1) /      24/
      data(iforest(i, -2,   1),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,   1) /     -24/
      data(iforest(i, -3,   1),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -3,   1) /       5/
      data(iforest(i, -4,   1),i=1,2) / -3, -2/          !  TMASS   TWIDTH  
      data tprid(  -4,   1) /      -6/
      data(iforest(i, -5,   1),i=1,2) / -4, -1/          !  BMASS   ZERO    
      data tprid(  -5,   1) /      -5/
      data(iforest(i, -6,   1),i=1,2) / -5,  7/          !  
c   Graph      2
      data mapconfig(   2) /   2/
      data(iforest(i, -1,   2),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   2) /      24/
      data(iforest(i, -2,   2),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,   2) /     -24/
      data(iforest(i, -3,   2),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data sprop(  -3,   2) /      -6/
      data(iforest(i, -4,   2),i=1,2) /  1, -3/          !  TMASS   TWIDTH  
      data tprid(  -4,   2) /      -6/
      data(iforest(i, -5,   2),i=1,2) / -4, -1/          !  BMASS   ZERO    
      data tprid(  -5,   2) /      -5/
      data(iforest(i, -6,   2),i=1,2) / -5,  7/          !  
c   Graph      3
      data mapconfig(   3) /   3/
      data(iforest(i, -1,   3),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   3) /      24/
      data(iforest(i, -2,   3),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,   3) /       6/
      data(iforest(i, -3,   3),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   3) /     -24/
      data(iforest(i, -4,   3),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -4,   3) /       5/
      data(iforest(i, -5,   3),i=1,2) / -4, -3/          !  TMASS   TWIDTH  
      data tprid(  -5,   3) /      -6/
      data(iforest(i, -6,   3),i=1,2) / -5, -2/          !  
c   Graph      4
      data mapconfig(   4) /   4/
      data(iforest(i, -1,   4),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   4) /      24/
      data(iforest(i, -2,   4),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,   4) /       6/
      data(iforest(i, -3,   4),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   4) /     -24/
      data(iforest(i, -4,   4),i=1,2) /  8, -3/          !  TMASS   TWIDTH  
      data sprop(  -4,   4) /      -6/
      data(iforest(i, -5,   4),i=1,2) /  1, -4/          !  TMASS   TWIDTH  
      data tprid(  -5,   4) /      -6/
      data(iforest(i, -6,   4),i=1,2) / -5, -2/          !  
c   Graph      5
      data mapconfig(   5) /   5/
      data(iforest(i, -1,   5),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   5) /      24/
      data(iforest(i, -2,   5),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,   5) /     -24/
      data(iforest(i, -3,   5),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -3,   5) /      -5/
      data(iforest(i, -4,   5),i=1,2) / -3, -1/          !  TMASS   TWIDTH  
      data tprid(  -4,   5) /      -6/
      data(iforest(i, -5,   5),i=1,2) / -4, -2/          !  BMASS   ZERO    
      data tprid(  -5,   5) /       5/
      data(iforest(i, -6,   5),i=1,2) / -5,  8/          !  
c   Graph      6
      data mapconfig(   6) /   6/
      data(iforest(i, -1,   6),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   6) /      24/
      data(iforest(i, -2,   6),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,   6) /     -24/
      data(iforest(i, -3,   6),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data sprop(  -3,   6) /      -6/
      data(iforest(i, -4,   6),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -4,   6) /      -5/
      data(iforest(i, -5,   6),i=1,2) / -4, -1/          !  TMASS   TWIDTH  
      data tprid(  -5,   6) /      -6/
      data(iforest(i, -6,   6),i=1,2) / -5, -3/          !  
c   Graph      7
      data mapconfig(   7) /   7/
      data(iforest(i, -1,   7),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   7) /      24/
      data(iforest(i, -2,   7),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,   7) /       6/
      data(iforest(i, -3,   7),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   7) /     -24/
      data(iforest(i, -4,   7),i=1,2) /  1, -2/          !  TMASS   TWIDTH  
      data tprid(  -4,   7) /      -6/
      data(iforest(i, -5,   7),i=1,2) / -4, -3/          !  BMASS   ZERO    
      data tprid(  -5,   7) /       5/
      data(iforest(i, -6,   7),i=1,2) / -5,  8/          !  
c   Graph      8
      data mapconfig(   8) /   8/
      data(iforest(i, -1,   8),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   8) /      24/
      data(iforest(i, -2,   8),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,   8) /       6/
      data(iforest(i, -3,   8),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,   8) /     -24/
      data(iforest(i, -4,   8),i=1,2) /  8, -3/          !  TMASS   TWIDTH  
      data sprop(  -4,   8) /      -6/
      data(iforest(i, -5,   8),i=1,2) /  1, -2/          !  TMASS   TWIDTH  
      data tprid(  -5,   8) /      -6/
      data(iforest(i, -6,   8),i=1,2) / -5, -4/          !  
c   Graph      9
      data mapconfig(   9) /   9/
      data(iforest(i, -1,   9),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,   9) /      24/
      data(iforest(i, -2,   9),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,   9) /     -24/
      data(iforest(i, -3,   9),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,   9) /      22/
      data(iforest(i, -4,   9),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -4,   9) /      -5/
      data(iforest(i, -5,   9),i=1,2) / -4, -3/          !  BMASS   ZERO    
      data tprid(  -5,   9) /       5/
      data(iforest(i, -6,   9),i=1,2) / -5,  8/          !  
c   Graph     10
      data mapconfig(  10) /  10/
      data(iforest(i, -1,  10),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  10) /      24/
      data(iforest(i, -2,  10),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  10) /     -24/
      data(iforest(i, -3,  10),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  10) /      23/
      data(iforest(i, -4,  10),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -4,  10) /      -5/
      data(iforest(i, -5,  10),i=1,2) / -4, -3/          !  BMASS   ZERO    
      data tprid(  -5,  10) /       5/
      data(iforest(i, -6,  10),i=1,2) / -5,  8/          !  
c   Graph     11
      data mapconfig(  11) /  11/
      data(iforest(i, -1,  11),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  11) /      24/
      data(iforest(i, -2,  11),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  11) /     -24/
      data(iforest(i, -3,  11),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  11) /      25/
      data(iforest(i, -4,  11),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -4,  11) /      -5/
      data(iforest(i, -5,  11),i=1,2) / -4, -3/          !  BMASS   ZERO    
      data tprid(  -5,  11) /       5/
      data(iforest(i, -6,  11),i=1,2) / -5,  8/          !  
c   Graph     12
      data mapconfig(  12) /  12/
      data(iforest(i, -1,  12),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  12) /      24/
      data(iforest(i, -2,  12),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  12) /     -24/
      data(iforest(i, -3,  12),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  12) /      22/
      data(iforest(i, -4,  12),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  12) /      -5/
      data(iforest(i, -5,  12),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -5,  12) /      -5/
      data(iforest(i, -6,  12),i=1,2) / -5, -4/          !  
c   Graph     13
      data mapconfig(  13) /  13/
      data(iforest(i, -1,  13),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  13) /      24/
      data(iforest(i, -2,  13),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  13) /     -24/
      data(iforest(i, -3,  13),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  13) /      23/
      data(iforest(i, -4,  13),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  13) /      -5/
      data(iforest(i, -5,  13),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -5,  13) /      -5/
      data(iforest(i, -6,  13),i=1,2) / -5, -4/          !  
c   Graph     14
      data mapconfig(  14) /  14/
      data(iforest(i, -1,  14),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  14) /      24/
      data(iforest(i, -2,  14),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  14) /     -24/
      data(iforest(i, -3,  14),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  14) /      25/
      data(iforest(i, -4,  14),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  14) /      -5/
      data(iforest(i, -5,  14),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -5,  14) /      -5/
      data(iforest(i, -6,  14),i=1,2) / -5, -4/          !  
c   Graph     15
      data mapconfig(  15) /  15/
      data(iforest(i, -1,  15),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  15) /      24/
      data(iforest(i, -2,  15),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  15) /     -24/
      data(iforest(i, -3,  15),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data sprop(  -3,  15) /      -6/
      data(iforest(i, -4,  15),i=1,2) / -3, -1/          !  BMASS   ZERO    
      data sprop(  -4,  15) /      -5/
      data(iforest(i, -5,  15),i=1,2) /  1,  7/          !  BMASS   ZERO    
      data tprid(  -5,  15) /      -5/
      data(iforest(i, -6,  15),i=1,2) / -5, -4/          !  
c   Graph     16
      data mapconfig(  16) /  16/
      data(iforest(i, -1,  16),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  16) /      24/
      data(iforest(i, -2,  16),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  16) /     -24/
      data(iforest(i, -3,  16),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  16) /      22/
      data(iforest(i, -4,  16),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -4,  16) /       5/
      data(iforest(i, -5,  16),i=1,2) / -4, -3/          !  BMASS   ZERO    
      data tprid(  -5,  16) /      -5/
      data(iforest(i, -6,  16),i=1,2) / -5,  7/          !  
c   Graph     17
      data mapconfig(  17) /  17/
      data(iforest(i, -1,  17),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  17) /      24/
      data(iforest(i, -2,  17),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  17) /     -24/
      data(iforest(i, -3,  17),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  17) /      23/
      data(iforest(i, -4,  17),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -4,  17) /       5/
      data(iforest(i, -5,  17),i=1,2) / -4, -3/          !  BMASS   ZERO    
      data tprid(  -5,  17) /      -5/
      data(iforest(i, -6,  17),i=1,2) / -5,  7/          !  
c   Graph     18
      data mapconfig(  18) /  18/
      data(iforest(i, -1,  18),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  18) /      24/
      data(iforest(i, -2,  18),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  18) /     -24/
      data(iforest(i, -3,  18),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  18) /      25/
      data(iforest(i, -4,  18),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -4,  18) /       5/
      data(iforest(i, -5,  18),i=1,2) / -4, -3/          !  BMASS   ZERO    
      data tprid(  -5,  18) /      -5/
      data(iforest(i, -6,  18),i=1,2) / -5,  7/          !  
c   Graph     19
      data mapconfig(  19) /  19/
      data(iforest(i, -1,  19),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  19) /      24/
      data(iforest(i, -2,  19),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  19) /     -24/
      data(iforest(i, -3,  19),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  19) /      22/
      data(iforest(i, -4,  19),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  19) /      -5/
      data(iforest(i, -5,  19),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  19) /      -5/
      data(iforest(i, -6,  19),i=1,2) / -5,  7/          !  
c   Graph     20
      data mapconfig(  20) /  20/
      data(iforest(i, -1,  20),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  20) /      24/
      data(iforest(i, -2,  20),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  20) /     -24/
      data(iforest(i, -3,  20),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  20) /      23/
      data(iforest(i, -4,  20),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  20) /      -5/
      data(iforest(i, -5,  20),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  20) /      -5/
      data(iforest(i, -6,  20),i=1,2) / -5,  7/          !  
c   Graph     21
      data mapconfig(  21) /  21/
      data(iforest(i, -1,  21),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  21) /      24/
      data(iforest(i, -2,  21),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  21) /     -24/
      data(iforest(i, -3,  21),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  21) /      25/
      data(iforest(i, -4,  21),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  21) /      -5/
      data(iforest(i, -5,  21),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  21) /      -5/
      data(iforest(i, -6,  21),i=1,2) / -5,  7/          !  
c   Graph     22
      data mapconfig(  22) /  22/
      data(iforest(i, -1,  22),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  22) /      24/
      data(iforest(i, -2,  22),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  22) /     -24/
      data(iforest(i, -3,  22),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data sprop(  -3,  22) /      -6/
      data(iforest(i, -4,  22),i=1,2) / -3, -1/          !  BMASS   ZERO    
      data sprop(  -4,  22) /      -5/
      data(iforest(i, -5,  22),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  22) /      -5/
      data(iforest(i, -6,  22),i=1,2) / -5,  7/          !  
c   Graph     23
      data mapconfig(  23) /  23/
      data(iforest(i, -1,  23),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  23) /      24/
      data(iforest(i, -2,  23),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,  23) /       6/
      data(iforest(i, -3,  23),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,  23) /     -24/
      data(iforest(i, -4,  23),i=1,2) / -3, -2/          !  BMASS   ZERO    
      data sprop(  -4,  23) /       5/
      data(iforest(i, -5,  23),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -5,  23) /       5/
      data(iforest(i, -6,  23),i=1,2) / -5, -4/          !  
c   Graph     24
      data mapconfig(  24) /  24/
      data(iforest(i, -1,  24),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  24) /      24/
      data(iforest(i, -2,  24),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,  24) /       6/
      data(iforest(i, -3,  24),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,  24) /     -24/
      data(iforest(i, -4,  24),i=1,2) / -3, -2/          !  BMASS   ZERO    
      data sprop(  -4,  24) /       5/
      data(iforest(i, -5,  24),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  24) /       5/
      data(iforest(i, -6,  24),i=1,2) / -5,  8/          !  
c   Graph     25
      data mapconfig(  25) /  25/
      data(iforest(i, -1,  25),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  25) /      24/
      data(iforest(i, -2,  25),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,  25) /       6/
      data(iforest(i, -3,  25),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,  25) /     -24/
      data(iforest(i, -4,  25),i=1,2) / -3, -2/          !  BMASS   ZERO    
      data sprop(  -4,  25) /       5/
      data(iforest(i, -5,  25),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,  25) /      21/
c   Graph     26
      data mapconfig(  26) /  26/
      data(iforest(i, -1,  26),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  26) /      24/
      data(iforest(i, -2,  26),i=1,2) /  7, -1/          !  TMASS   TWIDTH  
      data sprop(  -2,  26) /       6/
      data(iforest(i, -3,  26),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -3,  26) /     -24/
      data(iforest(i, -4,  26),i=1,2) /  8, -3/          !  TMASS   TWIDTH  
      data sprop(  -4,  26) /      -6/
      data(iforest(i, -5,  26),i=1,2) / -4, -2/          !  ZERO    ZERO    
      data sprop(  -5,  26) /      21/
c   Graph     27
      data mapconfig(  27) /  27/
      data(iforest(i, -1,  27),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  27) /      24/
      data(iforest(i, -2,  27),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  27) /     -24/
      data(iforest(i, -3,  27),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  27) /      22/
      data(iforest(i, -4,  27),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  27) /       5/
      data(iforest(i, -5,  27),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -5,  27) /       5/
      data(iforest(i, -6,  27),i=1,2) / -5, -4/          !  
c   Graph     28
      data mapconfig(  28) /  28/
      data(iforest(i, -1,  28),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  28) /      24/
      data(iforest(i, -2,  28),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  28) /     -24/
      data(iforest(i, -3,  28),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  28) /      23/
      data(iforest(i, -4,  28),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  28) /       5/
      data(iforest(i, -5,  28),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -5,  28) /       5/
      data(iforest(i, -6,  28),i=1,2) / -5, -4/          !  
c   Graph     29
      data mapconfig(  29) /  29/
      data(iforest(i, -1,  29),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  29) /      24/
      data(iforest(i, -2,  29),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  29) /     -24/
      data(iforest(i, -3,  29),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  29) /      25/
      data(iforest(i, -4,  29),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  29) /       5/
      data(iforest(i, -5,  29),i=1,2) /  1,  8/          !  BMASS   ZERO    
      data tprid(  -5,  29) /       5/
      data(iforest(i, -6,  29),i=1,2) / -5, -4/          !  
c   Graph     30
      data mapconfig(  30) /  30/
      data(iforest(i, -1,  30),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  30) /      24/
      data(iforest(i, -2,  30),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  30) /     -24/
      data(iforest(i, -3,  30),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  30) /      22/
      data(iforest(i, -4,  30),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  30) /       5/
      data(iforest(i, -5,  30),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  30) /       5/
      data(iforest(i, -6,  30),i=1,2) / -5,  8/          !  
c   Graph     31
      data mapconfig(  31) /  31/
      data(iforest(i, -1,  31),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  31) /      24/
      data(iforest(i, -2,  31),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  31) /     -24/
      data(iforest(i, -3,  31),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  31) /      23/
      data(iforest(i, -4,  31),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  31) /       5/
      data(iforest(i, -5,  31),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  31) /       5/
      data(iforest(i, -6,  31),i=1,2) / -5,  8/          !  
c   Graph     32
      data mapconfig(  32) /  32/
      data(iforest(i, -1,  32),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  32) /      24/
      data(iforest(i, -2,  32),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  32) /     -24/
      data(iforest(i, -3,  32),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  32) /      25/
      data(iforest(i, -4,  32),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  32) /       5/
      data(iforest(i, -5,  32),i=1,2) /  1, -4/          !  BMASS   ZERO    
      data tprid(  -5,  32) /       5/
      data(iforest(i, -6,  32),i=1,2) / -5,  8/          !  
c   Graph     33
      data mapconfig(  33) /  33/
      data(iforest(i, -1,  33),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  33) /      24/
      data(iforest(i, -2,  33),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  33) /     -24/
      data(iforest(i, -3,  33),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  33) /      22/
      data(iforest(i, -4,  33),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  33) /       5/
      data(iforest(i, -5,  33),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,  33) /      21/
c   Graph     34
      data mapconfig(  34) /  34/
      data(iforest(i, -1,  34),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  34) /      24/
      data(iforest(i, -2,  34),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  34) /     -24/
      data(iforest(i, -3,  34),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  34) /      23/
      data(iforest(i, -4,  34),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  34) /       5/
      data(iforest(i, -5,  34),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,  34) /      21/
c   Graph     35
      data mapconfig(  35) /  35/
      data(iforest(i, -1,  35),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  35) /      24/
      data(iforest(i, -2,  35),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  35) /     -24/
      data(iforest(i, -3,  35),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  35) /      25/
      data(iforest(i, -4,  35),i=1,2) /  7, -3/          !  BMASS   ZERO    
      data sprop(  -4,  35) /       5/
      data(iforest(i, -5,  35),i=1,2) /  8, -4/          !  ZERO    ZERO    
      data sprop(  -5,  35) /      21/
c   Graph     36
      data mapconfig(  36) /  36/
      data(iforest(i, -1,  36),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  36) /      24/
      data(iforest(i, -2,  36),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  36) /     -24/
      data(iforest(i, -3,  36),i=1,2) /  8, -2/          !  TMASS   TWIDTH  
      data sprop(  -3,  36) /      -6/
      data(iforest(i, -4,  36),i=1,2) / -3, -1/          !  BMASS   ZERO    
      data sprop(  -4,  36) /      -5/
      data(iforest(i, -5,  36),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  36) /      21/
c   Graph     37
      data mapconfig(  37) /  37/
      data(iforest(i, -1,  37),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  37) /      24/
      data(iforest(i, -2,  37),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  37) /     -24/
      data(iforest(i, -3,  37),i=1,2) / -2, -1/          !  ZERO    AWIDTH  
      data sprop(  -3,  37) /      22/
      data(iforest(i, -4,  37),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  37) /      -5/
      data(iforest(i, -5,  37),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  37) /      21/
c   Graph     38
      data mapconfig(  38) /  38/
      data(iforest(i, -1,  38),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  38) /      24/
      data(iforest(i, -2,  38),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  38) /     -24/
      data(iforest(i, -3,  38),i=1,2) / -2, -1/          !  ZMASS   ZWIDTH  
      data sprop(  -3,  38) /      23/
      data(iforest(i, -4,  38),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  38) /      -5/
      data(iforest(i, -5,  38),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  38) /      21/
c   Graph     39
      data mapconfig(  39) /  39/
      data(iforest(i, -1,  39),i=1,2) /  4,  3/          !  WMASS   WWIDTH  
      data sprop(  -1,  39) /      24/
      data(iforest(i, -2,  39),i=1,2) /  6,  5/          !  WMASS   WWIDTH  
      data sprop(  -2,  39) /     -24/
      data(iforest(i, -3,  39),i=1,2) / -2, -1/          !  HMASS   HWIDTH  
      data sprop(  -3,  39) /      25/
      data(iforest(i, -4,  39),i=1,2) /  8, -3/          !  BMASS   ZERO    
      data sprop(  -4,  39) /      -5/
      data(iforest(i, -5,  39),i=1,2) /  7, -4/          !  ZERO    ZERO    
      data sprop(  -5,  39) /      21/
      data mapconfig(   0) /  39/
