      SUBROUTINE SMATRIX(P1,ANS)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : g g -> b w+ b~ w-  
C  
C Crossing   1 is g g -> b w+ b~ w-  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      Include "genps.inc"
      Include "nexternal.inc"
      Include "maxamps.inc"
      INTEGER                 NCOMB,     NCROSS         
      PARAMETER (             NCOMB= 144, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T, P(0:3,NEXTERNAL)
      REAL*8 MATRIX
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL), I
      LOGICAL GOODHEL(NCOMB,NCROSS)
      INTEGER NGRAPHS
      REAL*8 hwgt, xtot, xtry, xrej, xr, yfrac(0:ncomb)
      INTEGER idum, ngood, igood(ncomb), jhel, j, jj
      LOGICAL warned
      REAL     xran1
      EXTERNAL xran1
C  
C GLOBAL VARIABLES
C  
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps/  amp2,       jamp2

      character*79         hel_buff
      common/to_helicity/  hel_buff

      REAL*8 POL(2)
      common/to_polarization/ POL

      integer          isum_hel
      logical                    multi_channel
      common/to_matrix/isum_hel, multi_channel
      INTEGER MAPCONFIG(0:LMAXCONFIGS), ICONFIG
      common/to_mconfigs/mapconfig, iconfig
      DATA NTRY,IDUM /0,-1/
      DATA xtry, xrej, ngood /0,0,0/
      DATA warned, isum_hel/.false.,0/
      DATA multi_channel/.true./
      SAVE yfrac, igood, jhel
      DATA NGRAPHS /   39/          
      DATA jamp2(0) /   2/          
      DATA GOODHEL/THEL*.FALSE./
      DATA (NHEL(IHEL,   1),IHEL=1, 6) /-1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,   2),IHEL=1, 6) /-1,-1,-1,-1,-1, 0/
      DATA (NHEL(IHEL,   3),IHEL=1, 6) /-1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,   4),IHEL=1, 6) /-1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,   5),IHEL=1, 6) /-1,-1,-1,-1, 1, 0/
      DATA (NHEL(IHEL,   6),IHEL=1, 6) /-1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,   7),IHEL=1, 6) /-1,-1,-1, 0,-1,-1/
      DATA (NHEL(IHEL,   8),IHEL=1, 6) /-1,-1,-1, 0,-1, 0/
      DATA (NHEL(IHEL,   9),IHEL=1, 6) /-1,-1,-1, 0,-1, 1/
      DATA (NHEL(IHEL,  10),IHEL=1, 6) /-1,-1,-1, 0, 1,-1/
      DATA (NHEL(IHEL,  11),IHEL=1, 6) /-1,-1,-1, 0, 1, 0/
      DATA (NHEL(IHEL,  12),IHEL=1, 6) /-1,-1,-1, 0, 1, 1/
      DATA (NHEL(IHEL,  13),IHEL=1, 6) /-1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  14),IHEL=1, 6) /-1,-1,-1, 1,-1, 0/
      DATA (NHEL(IHEL,  15),IHEL=1, 6) /-1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  16),IHEL=1, 6) /-1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  17),IHEL=1, 6) /-1,-1,-1, 1, 1, 0/
      DATA (NHEL(IHEL,  18),IHEL=1, 6) /-1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  19),IHEL=1, 6) /-1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  20),IHEL=1, 6) /-1,-1, 1,-1,-1, 0/
      DATA (NHEL(IHEL,  21),IHEL=1, 6) /-1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  22),IHEL=1, 6) /-1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  23),IHEL=1, 6) /-1,-1, 1,-1, 1, 0/
      DATA (NHEL(IHEL,  24),IHEL=1, 6) /-1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  25),IHEL=1, 6) /-1,-1, 1, 0,-1,-1/
      DATA (NHEL(IHEL,  26),IHEL=1, 6) /-1,-1, 1, 0,-1, 0/
      DATA (NHEL(IHEL,  27),IHEL=1, 6) /-1,-1, 1, 0,-1, 1/
      DATA (NHEL(IHEL,  28),IHEL=1, 6) /-1,-1, 1, 0, 1,-1/
      DATA (NHEL(IHEL,  29),IHEL=1, 6) /-1,-1, 1, 0, 1, 0/
      DATA (NHEL(IHEL,  30),IHEL=1, 6) /-1,-1, 1, 0, 1, 1/
      DATA (NHEL(IHEL,  31),IHEL=1, 6) /-1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  32),IHEL=1, 6) /-1,-1, 1, 1,-1, 0/
      DATA (NHEL(IHEL,  33),IHEL=1, 6) /-1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  34),IHEL=1, 6) /-1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  35),IHEL=1, 6) /-1,-1, 1, 1, 1, 0/
      DATA (NHEL(IHEL,  36),IHEL=1, 6) /-1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  37),IHEL=1, 6) /-1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  38),IHEL=1, 6) /-1, 1,-1,-1,-1, 0/
      DATA (NHEL(IHEL,  39),IHEL=1, 6) /-1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  40),IHEL=1, 6) /-1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  41),IHEL=1, 6) /-1, 1,-1,-1, 1, 0/
      DATA (NHEL(IHEL,  42),IHEL=1, 6) /-1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  43),IHEL=1, 6) /-1, 1,-1, 0,-1,-1/
      DATA (NHEL(IHEL,  44),IHEL=1, 6) /-1, 1,-1, 0,-1, 0/
      DATA (NHEL(IHEL,  45),IHEL=1, 6) /-1, 1,-1, 0,-1, 1/
      DATA (NHEL(IHEL,  46),IHEL=1, 6) /-1, 1,-1, 0, 1,-1/
      DATA (NHEL(IHEL,  47),IHEL=1, 6) /-1, 1,-1, 0, 1, 0/
      DATA (NHEL(IHEL,  48),IHEL=1, 6) /-1, 1,-1, 0, 1, 1/
      DATA (NHEL(IHEL,  49),IHEL=1, 6) /-1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  50),IHEL=1, 6) /-1, 1,-1, 1,-1, 0/
      DATA (NHEL(IHEL,  51),IHEL=1, 6) /-1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  52),IHEL=1, 6) /-1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  53),IHEL=1, 6) /-1, 1,-1, 1, 1, 0/
      DATA (NHEL(IHEL,  54),IHEL=1, 6) /-1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  55),IHEL=1, 6) /-1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  56),IHEL=1, 6) /-1, 1, 1,-1,-1, 0/
      DATA (NHEL(IHEL,  57),IHEL=1, 6) /-1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  58),IHEL=1, 6) /-1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  59),IHEL=1, 6) /-1, 1, 1,-1, 1, 0/
      DATA (NHEL(IHEL,  60),IHEL=1, 6) /-1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  61),IHEL=1, 6) /-1, 1, 1, 0,-1,-1/
      DATA (NHEL(IHEL,  62),IHEL=1, 6) /-1, 1, 1, 0,-1, 0/
      DATA (NHEL(IHEL,  63),IHEL=1, 6) /-1, 1, 1, 0,-1, 1/
      DATA (NHEL(IHEL,  64),IHEL=1, 6) /-1, 1, 1, 0, 1,-1/
      DATA (NHEL(IHEL,  65),IHEL=1, 6) /-1, 1, 1, 0, 1, 0/
      DATA (NHEL(IHEL,  66),IHEL=1, 6) /-1, 1, 1, 0, 1, 1/
      DATA (NHEL(IHEL,  67),IHEL=1, 6) /-1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL,  68),IHEL=1, 6) /-1, 1, 1, 1,-1, 0/
      DATA (NHEL(IHEL,  69),IHEL=1, 6) /-1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL,  70),IHEL=1, 6) /-1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL,  71),IHEL=1, 6) /-1, 1, 1, 1, 1, 0/
      DATA (NHEL(IHEL,  72),IHEL=1, 6) /-1, 1, 1, 1, 1, 1/
      DATA (NHEL(IHEL,  73),IHEL=1, 6) / 1,-1,-1,-1,-1,-1/
      DATA (NHEL(IHEL,  74),IHEL=1, 6) / 1,-1,-1,-1,-1, 0/
      DATA (NHEL(IHEL,  75),IHEL=1, 6) / 1,-1,-1,-1,-1, 1/
      DATA (NHEL(IHEL,  76),IHEL=1, 6) / 1,-1,-1,-1, 1,-1/
      DATA (NHEL(IHEL,  77),IHEL=1, 6) / 1,-1,-1,-1, 1, 0/
      DATA (NHEL(IHEL,  78),IHEL=1, 6) / 1,-1,-1,-1, 1, 1/
      DATA (NHEL(IHEL,  79),IHEL=1, 6) / 1,-1,-1, 0,-1,-1/
      DATA (NHEL(IHEL,  80),IHEL=1, 6) / 1,-1,-1, 0,-1, 0/
      DATA (NHEL(IHEL,  81),IHEL=1, 6) / 1,-1,-1, 0,-1, 1/
      DATA (NHEL(IHEL,  82),IHEL=1, 6) / 1,-1,-1, 0, 1,-1/
      DATA (NHEL(IHEL,  83),IHEL=1, 6) / 1,-1,-1, 0, 1, 0/
      DATA (NHEL(IHEL,  84),IHEL=1, 6) / 1,-1,-1, 0, 1, 1/
      DATA (NHEL(IHEL,  85),IHEL=1, 6) / 1,-1,-1, 1,-1,-1/
      DATA (NHEL(IHEL,  86),IHEL=1, 6) / 1,-1,-1, 1,-1, 0/
      DATA (NHEL(IHEL,  87),IHEL=1, 6) / 1,-1,-1, 1,-1, 1/
      DATA (NHEL(IHEL,  88),IHEL=1, 6) / 1,-1,-1, 1, 1,-1/
      DATA (NHEL(IHEL,  89),IHEL=1, 6) / 1,-1,-1, 1, 1, 0/
      DATA (NHEL(IHEL,  90),IHEL=1, 6) / 1,-1,-1, 1, 1, 1/
      DATA (NHEL(IHEL,  91),IHEL=1, 6) / 1,-1, 1,-1,-1,-1/
      DATA (NHEL(IHEL,  92),IHEL=1, 6) / 1,-1, 1,-1,-1, 0/
      DATA (NHEL(IHEL,  93),IHEL=1, 6) / 1,-1, 1,-1,-1, 1/
      DATA (NHEL(IHEL,  94),IHEL=1, 6) / 1,-1, 1,-1, 1,-1/
      DATA (NHEL(IHEL,  95),IHEL=1, 6) / 1,-1, 1,-1, 1, 0/
      DATA (NHEL(IHEL,  96),IHEL=1, 6) / 1,-1, 1,-1, 1, 1/
      DATA (NHEL(IHEL,  97),IHEL=1, 6) / 1,-1, 1, 0,-1,-1/
      DATA (NHEL(IHEL,  98),IHEL=1, 6) / 1,-1, 1, 0,-1, 0/
      DATA (NHEL(IHEL,  99),IHEL=1, 6) / 1,-1, 1, 0,-1, 1/
      DATA (NHEL(IHEL, 100),IHEL=1, 6) / 1,-1, 1, 0, 1,-1/
      DATA (NHEL(IHEL, 101),IHEL=1, 6) / 1,-1, 1, 0, 1, 0/
      DATA (NHEL(IHEL, 102),IHEL=1, 6) / 1,-1, 1, 0, 1, 1/
      DATA (NHEL(IHEL, 103),IHEL=1, 6) / 1,-1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 104),IHEL=1, 6) / 1,-1, 1, 1,-1, 0/
      DATA (NHEL(IHEL, 105),IHEL=1, 6) / 1,-1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 106),IHEL=1, 6) / 1,-1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 107),IHEL=1, 6) / 1,-1, 1, 1, 1, 0/
      DATA (NHEL(IHEL, 108),IHEL=1, 6) / 1,-1, 1, 1, 1, 1/
      DATA (NHEL(IHEL, 109),IHEL=1, 6) / 1, 1,-1,-1,-1,-1/
      DATA (NHEL(IHEL, 110),IHEL=1, 6) / 1, 1,-1,-1,-1, 0/
      DATA (NHEL(IHEL, 111),IHEL=1, 6) / 1, 1,-1,-1,-1, 1/
      DATA (NHEL(IHEL, 112),IHEL=1, 6) / 1, 1,-1,-1, 1,-1/
      DATA (NHEL(IHEL, 113),IHEL=1, 6) / 1, 1,-1,-1, 1, 0/
      DATA (NHEL(IHEL, 114),IHEL=1, 6) / 1, 1,-1,-1, 1, 1/
      DATA (NHEL(IHEL, 115),IHEL=1, 6) / 1, 1,-1, 0,-1,-1/
      DATA (NHEL(IHEL, 116),IHEL=1, 6) / 1, 1,-1, 0,-1, 0/
      DATA (NHEL(IHEL, 117),IHEL=1, 6) / 1, 1,-1, 0,-1, 1/
      DATA (NHEL(IHEL, 118),IHEL=1, 6) / 1, 1,-1, 0, 1,-1/
      DATA (NHEL(IHEL, 119),IHEL=1, 6) / 1, 1,-1, 0, 1, 0/
      DATA (NHEL(IHEL, 120),IHEL=1, 6) / 1, 1,-1, 0, 1, 1/
      DATA (NHEL(IHEL, 121),IHEL=1, 6) / 1, 1,-1, 1,-1,-1/
      DATA (NHEL(IHEL, 122),IHEL=1, 6) / 1, 1,-1, 1,-1, 0/
      DATA (NHEL(IHEL, 123),IHEL=1, 6) / 1, 1,-1, 1,-1, 1/
      DATA (NHEL(IHEL, 124),IHEL=1, 6) / 1, 1,-1, 1, 1,-1/
      DATA (NHEL(IHEL, 125),IHEL=1, 6) / 1, 1,-1, 1, 1, 0/
      DATA (NHEL(IHEL, 126),IHEL=1, 6) / 1, 1,-1, 1, 1, 1/
      DATA (NHEL(IHEL, 127),IHEL=1, 6) / 1, 1, 1,-1,-1,-1/
      DATA (NHEL(IHEL, 128),IHEL=1, 6) / 1, 1, 1,-1,-1, 0/
      DATA (NHEL(IHEL, 129),IHEL=1, 6) / 1, 1, 1,-1,-1, 1/
      DATA (NHEL(IHEL, 130),IHEL=1, 6) / 1, 1, 1,-1, 1,-1/
      DATA (NHEL(IHEL, 131),IHEL=1, 6) / 1, 1, 1,-1, 1, 0/
      DATA (NHEL(IHEL, 132),IHEL=1, 6) / 1, 1, 1,-1, 1, 1/
      DATA (NHEL(IHEL, 133),IHEL=1, 6) / 1, 1, 1, 0,-1,-1/
      DATA (NHEL(IHEL, 134),IHEL=1, 6) / 1, 1, 1, 0,-1, 0/
      DATA (NHEL(IHEL, 135),IHEL=1, 6) / 1, 1, 1, 0,-1, 1/
      DATA (NHEL(IHEL, 136),IHEL=1, 6) / 1, 1, 1, 0, 1,-1/
      DATA (NHEL(IHEL, 137),IHEL=1, 6) / 1, 1, 1, 0, 1, 0/
      DATA (NHEL(IHEL, 138),IHEL=1, 6) / 1, 1, 1, 0, 1, 1/
      DATA (NHEL(IHEL, 139),IHEL=1, 6) / 1, 1, 1, 1,-1,-1/
      DATA (NHEL(IHEL, 140),IHEL=1, 6) / 1, 1, 1, 1,-1, 0/
      DATA (NHEL(IHEL, 141),IHEL=1, 6) / 1, 1, 1, 1,-1, 1/
      DATA (NHEL(IHEL, 142),IHEL=1, 6) / 1, 1, 1, 1, 1,-1/
      DATA (NHEL(IHEL, 143),IHEL=1, 6) / 1, 1, 1, 1, 1, 0/
      DATA (NHEL(IHEL, 144),IHEL=1, 6) / 1, 1, 1, 1, 1, 1/
      DATA (  IC(IHEL,  1),IHEL=1, 6) / 1, 2, 3, 4, 5, 6/
      DATA (IDEN(IHEL),IHEL=  1,  1) / 256/
C --------
C USER SET
C --------
      include 'thr.inc'
      include 'kfac.inc'
C ----------
C BEGIN CODE
C ----------
      NTRY=NTRY+1
      DO IPROC=1,NCROSS
      CALL SWITCHMOM(P1,P,IC(1,IPROC),JC,NEXTERNAL)
      DO IHEL=1,NEXTERNAL
         JC(IHEL) = +1
      ENDDO
       
      IF (multi_channel) THEN
          DO IHEL=1,NGRAPHS
              amp2(ihel)=0d0
              jamp2(ihel)=0d0
          ENDDO
          DO IHEL=1,int(jamp2(0))
              jamp2(ihel)=0d0
          ENDDO
      ENDIF
      ANS(IPROC) = 0D0
      write(hel_buff,'(16i5)') (0,i=1,nexternal)
      IF (ISUM_HEL .EQ. 0 .OR. NTRY .LT. 10) THEN
          DO IHEL=1,NCOMB
             IF (GOODHEL(IHEL,IPROC) .OR. NTRY .LT. 2) THEN
                 T=MATRIX(P ,NHEL(1,IHEL),JC(1))            
               DO JJ=1,nincoming
                 IF(POL(JJ).NE.1d0.AND.
     &              NHEL(JJ,IHEL).EQ.INT(SIGN(1d0,POL(JJ)))) THEN
                   T=T*ABS(POL(JJ))
                 ELSE IF(POL(JJ).NE.1d0)THEN
                   T=T*(2d0-ABS(POL(JJ)))
                 ENDIF
               ENDDO
               ANS(IPROC)=ANS(IPROC)+T
               IF (T .NE. 0D0 .AND. .NOT.    GOODHEL(IHEL,IPROC)) THEN
                   GOODHEL(IHEL,IPROC)=.TRUE.
                   NGOOD = NGOOD +1
                   IGOOD(NGOOD) = IHEL
               ENDIF
             ENDIF
          ENDDO
          JHEL = 1
          ISUM_HEL=MIN(ISUM_HEL,NGOOD)
      ELSE              !RANDOM HELICITY
          DO J=1,ISUM_HEL
              JHEL=JHEL+1
              IF (JHEL .GT. NGOOD) JHEL=1
              HWGT = REAL(NGOOD)/REAL(ISUM_HEL)
              IHEL = IGOOD(JHEL)
              T=MATRIX(P ,NHEL(1,IHEL),JC(1))            
              DO JJ=1,nincoming
                IF(POL(JJ).NE.1d0.AND.
     &             NHEL(JJ,IHEL).EQ.INT(SIGN(1d0,POL(JJ)))) THEN
                  T=T*ABS(POL(JJ))
                ELSE IF(POL(JJ).NE.1d0)THEN
                  T=T*(2d0-ABS(POL(JJ)))
                ENDIF
              ENDDO
              ANS(IPROC)=ANS(IPROC)+T*HWGT
          ENDDO
          IF (ISUM_HEL .EQ. 1) THEN
              WRITE(HEL_BUFF,'(16i5)')(NHEL(i,IHEL),i=1,nexternal)
          ENDIF
      ENDIF
      IF (MULTI_CHANNEL) THEN
          XTOT=0D0
          DO IHEL=1,MAPCONFIG(0)
              XTOT=XTOT+AMP2(MAPCONFIG(IHEL))
          ENDDO
          IF (XTOT.NE.0D0) THEN
              ANS(IPROC)=ANS(IPROC)*AMP2(MAPCONFIG(ICONFIG))/XTOT
          ELSE
              ANS(IPROC)=0D0
          ENDIF
      ENDIF
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))
      IF (IKF.EQ.1) ANS(IPROC)=ANS(IPROC)*KF(1)
      ENDDO
      END
       
       
      REAL*8 FUNCTION MATRIX(P,NHEL,IC)
C  
C Generated by MadGraph II                                              
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : g g -> b w+ b~ w-  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN 
      PARAMETER (NGRAPHS=  39,NEIGEN=  2) 
      include "genps.inc"
      include "nexternal.inc"
      include "maxamps.inc"
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=  54, NCOLOR=   2) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS)
C  
C GLOBAL VARIABLES
C  
      Double Precision amp2(maxamps), jamp2(0:maxamps)
      common/to_amps/  amp2,       jamp2
      include "coupl.inc"
C  
C COLOR DATA
C  
      DATA Denom(1  )/            3/                                       
      DATA (CF(i,1  ),i=1  ,2  ) /    2,   2/                            
C               T[ 3, 5, 2, 1]                                             
      DATA Denom(2  )/            3/                                       
      DATA (CF(i,2  ),i=1  ,2  ) /    2,   2/                            
C               T[ 3, 5, 1, 2]                                             
C --------
C USER SET
C --------
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      DOUBLE COMPLEX AMPT,AMPU,AMPS
      include 'coupling.inc'
      include 'thr.inc'
      include "kin_functions.inc"
C ----------
C BEGIN CODE
C ----------
      CALL VXXXXX(P(0,1   ),ZERO ,NHEL(1   ),-1*IC(1   ),W(1,1   ))        
      CALL VXXXXX(P(0,2   ),ZERO ,NHEL(2   ),-1*IC(2   ),W(1,2   ))        
      CALL OXXXXX(P(0,3   ),BMASS ,NHEL(3   ),+1*IC(3   ),W(1,3   ))       
      CALL VXXXXX(P(0,4   ),WMASS ,NHEL(4   ),+1*IC(4   ),W(1,4   ))       
      CALL IXXXXX(P(0,5   ),BMASS ,NHEL(5   ),-1*IC(5   ),W(1,5   ))       
      CALL VXXXXX(P(0,6   ),WMASS ,NHEL(6   ),+1*IC(6   ),W(1,6   ))       
      CALL FVOXXX(W(1,3   ),W(1,4   ),GWF   ,TMASS,TWIDTH,W(1,7   )) ! t
      CALL FVIXXX(W(1,5   ),W(1,6   ),GWF   ,TMASS,TWIDTH,W(1,8   )) ! t~
      MT1S = SumDot(P(0,3),P(0,4),+1D0)
      MT2S = SumDot(P(0,5),P(0,6),+1D0)
      S    = SumDot(P(0,1),P(0,2),+1D0)
C...  Resonant Amplitudes
      DO I = 1, NGRAPHS
         AMP(I) = DCMPLX(0D0,0D0)
      ENDDO
      CALL GGTT (W(1,1),W(1,2),W(1,7),W(1,8),AMPT,AMPU,AMPS,1)
      AMP(28) = AMPT
      AMP(22) = AMPU
      AMP(38) = AMPS
      IF (INR.EQ.0) GOTO 100
C...  Non-Resonant Amplitudes
      CALL FVOXXX(W(1,3   ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,7   ))     
      CALL FVIXXX(W(1,5   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,8   ))     
      CALL JIOXXX(W(1,8   ),W(1,7   ),GAD ,ZERO    ,AWIDTH  ,W(1,9   ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,9   ),GWWA ,AMP(1   ))           
      CALL JIOXXX(W(1,8   ),W(1,7   ),GZD ,ZMASS   ,ZWIDTH  ,W(1,10  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,10  ),GWWZ ,AMP(2   ))           
      CALL HIOXXX(W(1,8   ),W(1,7   ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     11  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,11  ),GWWH ,AMP(3   ))           
      CALL FVOXXX(W(1,7   ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,12  ))    
      CALL FVOXXX(W(1,12  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,13  ))     
      CALL IOVXXX(W(1,5   ),W(1,13  ),W(1,6   ),GWF ,AMP(4   ))            
      CALL IOVXXX(W(1,8   ),W(1,12  ),W(1,6   ),GWF ,AMP(5   ))            
      CALL FVOXXX(W(1,7   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,14  ))     
      CALL JIOXXX(W(1,5   ),W(1,14  ),GAD ,ZERO    ,AWIDTH  ,W(1,15  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,15  ),GWWA ,AMP(6   ))           
      CALL JIOXXX(W(1,5   ),W(1,14  ),GZD ,ZMASS   ,ZWIDTH  ,W(1,16  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,16  ),GWWZ ,AMP(7   ))           
      CALL HIOXXX(W(1,5   ),W(1,14  ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     17  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,17  ),GWWH ,AMP(8   ))           
      CALL FVOXXX(W(1,14  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,18  ))    
      CALL IOVXXX(W(1,5   ),W(1,18  ),W(1,6   ),GWF ,AMP(9   ))            
      CALL FVOXXX(W(1,3   ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,19  ))     
      CALL FVIXXX(W(1,5   ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,20  ))     
      CALL JIOXXX(W(1,20  ),W(1,19  ),GAD ,ZERO    ,AWIDTH  ,W(1,21  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,21  ),GWWA ,AMP(10  ))           
      CALL JIOXXX(W(1,20  ),W(1,19  ),GZD ,ZMASS   ,ZWIDTH  ,W(1,22  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,22  ),GWWZ ,AMP(11  ))           
      CALL HIOXXX(W(1,20  ),W(1,19  ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     23  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,23  ),GWWH ,AMP(12  ))           
      CALL FVOXXX(W(1,19  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,24  ))    
      CALL FVOXXX(W(1,24  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,25  ))     
      CALL IOVXXX(W(1,5   ),W(1,25  ),W(1,6   ),GWF ,AMP(13  ))            
      CALL IOVXXX(W(1,20  ),W(1,24  ),W(1,6   ),GWF ,AMP(14  ))            
      CALL FVOXXX(W(1,19  ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,26  ))     
      CALL JIOXXX(W(1,5   ),W(1,26  ),GAD ,ZERO    ,AWIDTH  ,W(1,27  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,27  ),GWWA ,AMP(15  ))           
      CALL JIOXXX(W(1,5   ),W(1,26  ),GZD ,ZMASS   ,ZWIDTH  ,W(1,28  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,28  ),GWWZ ,AMP(16  ))           
      CALL HIOXXX(W(1,5   ),W(1,26  ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     29  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,29  ),GWWH ,AMP(17  ))           
      CALL FVOXXX(W(1,26  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,30  ))    
      CALL IOVXXX(W(1,5   ),W(1,30  ),W(1,6   ),GWF ,AMP(18  ))            
      CALL FVIXXX(W(1,8   ),W(1,2   ),GG ,BMASS   ,ZERO    ,W(1,31  ))     
      CALL JIOXXX(W(1,31  ),W(1,3   ),GAD ,ZERO    ,AWIDTH  ,W(1,32  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,32  ),GWWA ,AMP(19  ))           
      CALL JIOXXX(W(1,31  ),W(1,3   ),GZD ,ZMASS   ,ZWIDTH  ,W(1,33  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,33  ),GWWZ ,AMP(20  ))           
      CALL HIOXXX(W(1,31  ),W(1,3   ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     34  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,34  ),GWWH ,AMP(21  ))           
      CALL FVOXXX(W(1,3   ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,35  ))    
      CALL FVOXXX(W(1,35  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,36  ))     
*     CALL FVOXXX(W(1,36  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,37  ))     
*     CALL IOVXXX(W(1,5   ),W(1,37  ),W(1,6   ),GWF ,AMP(22  ))            
      CALL IOVXXX(W(1,31  ),W(1,35  ),W(1,6   ),GWF ,AMP(23  ))            
      CALL IOVXXX(W(1,8   ),W(1,36  ),W(1,6   ),GWF ,AMP(24  ))            
      CALL FVIXXX(W(1,20  ),W(1,1   ),GG ,BMASS   ,ZERO    ,W(1,38  ))     
      CALL JIOXXX(W(1,38  ),W(1,3   ),GAD ,ZERO    ,AWIDTH  ,W(1,39  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,39  ),GWWA ,AMP(25  ))           
      CALL JIOXXX(W(1,38  ),W(1,3   ),GZD ,ZMASS   ,ZWIDTH  ,W(1,40  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,40  ),GWWZ ,AMP(26  ))           
      CALL HIOXXX(W(1,38  ),W(1,3   ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     41  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,41  ),GWWH ,AMP(27  ))           
      CALL FVOXXX(W(1,35  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,42  ))     
*     CALL FVOXXX(W(1,42  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,43  ))     
*     CALL IOVXXX(W(1,5   ),W(1,43  ),W(1,6   ),GWF ,AMP(28  ))            
      CALL IOVXXX(W(1,38  ),W(1,35  ),W(1,6   ),GWF ,AMP(29  ))            
      CALL IOVXXX(W(1,20  ),W(1,42  ),W(1,6   ),GWF ,AMP(30  ))            
      CALL JVVXXX(W(1,1   ),W(1,2   ),G ,ZERO    ,ZERO    ,W(1,44  ))      
      CALL FVOXXX(W(1,3   ),W(1,44  ),GG ,BMASS   ,ZERO    ,W(1,45  ))     
      CALL JIOXXX(W(1,5   ),W(1,45  ),GAD ,ZERO    ,AWIDTH  ,W(1,46  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,46  ),GWWA ,AMP(31  ))           
      CALL JIOXXX(W(1,5   ),W(1,45  ),GZD ,ZMASS   ,ZWIDTH  ,W(1,47  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,47  ),GWWZ ,AMP(32  ))           
      CALL HIOXXX(W(1,5   ),W(1,45  ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     48  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,48  ),GWWH ,AMP(33  ))           
      CALL FVOXXX(W(1,45  ),W(1,4   ),GWF ,TMASS   ,TWIDTH  ,W(1,49  ))    
      CALL IOVXXX(W(1,5   ),W(1,49  ),W(1,6   ),GWF ,AMP(34  ))            
      CALL FVIXXX(W(1,5   ),W(1,44  ),GG ,BMASS   ,ZERO    ,W(1,50  ))     
      CALL JIOXXX(W(1,50  ),W(1,3   ),GAD ,ZERO    ,AWIDTH  ,W(1,51  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,51  ),GWWA ,AMP(35  ))           
      CALL JIOXXX(W(1,50  ),W(1,3   ),GZD ,ZMASS   ,ZWIDTH  ,W(1,52  ))    
      CALL VVVXXX(W(1,6   ),W(1,4   ),W(1,52  ),GWWZ ,AMP(36  ))           
      CALL HIOXXX(W(1,50  ),W(1,3   ),GHBOT ,HMASS   ,HWIDTH  ,W(1,        
     &     53  ))                                                          
      CALL VVSXXX(W(1,6   ),W(1,4   ),W(1,53  ),GWWH ,AMP(37  ))           
*     CALL FVOXXX(W(1,35  ),W(1,44  ),GG ,TMASS   ,TWIDTH  ,W(1,54  ))     
*     CALL IOVXXX(W(1,5   ),W(1,54  ),W(1,6   ),GWF ,AMP(38  ))            
      CALL IOVXXX(W(1,50  ),W(1,35  ),W(1,6   ),GWF ,AMP(39  ))            
C.....
 100  CONTINUE
      JAMP(   1) = -AMP(   1)-AMP(   2)-AMP(   3)-AMP(   4)-AMP(   5)
     &             -AMP(   6)-AMP(   7)-AMP(   8)-AMP(   9)-AMP(  19)
     &             -AMP(  20)-AMP(  21)-AMP(  22)-AMP(  23)-AMP(  24)
     &             +AMP(  31)+AMP(  32)+AMP(  33)+AMP(  34)+AMP(  35)
     &             +AMP(  36)+AMP(  37)+AMP(  38)+AMP(  39)
      JAMP(   2) = -AMP(  10)-AMP(  11)-AMP(  12)-AMP(  13)-AMP(  14)
     &             -AMP(  15)-AMP(  16)-AMP(  17)-AMP(  18)-AMP(  25)
     &             -AMP(  26)-AMP(  27)-AMP(  28)-AMP(  29)-AMP(  30)
     &             -AMP(  31)-AMP(  32)-AMP(  33)-AMP(  34)-AMP(  35)
     &             -AMP(  36)-AMP(  37)-AMP(  38)-AMP(  39)
      MATRIX = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          MATRIX =MATRIX+ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO
      Do I = 1, NGRAPHS
          amp2(i)=amp2(i)+amp(i)*dconjg(amp(i))
      Enddo
      Do I = 1, NCOLOR
          Jamp2(i)=Jamp2(i)+Jamp(i)*dconjg(Jamp(i))
      Enddo
C      CALL GAUGECHECK(JAMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NCOLOR,NEIGEN) 
      END
       
       
      SUBROUTINE GGTT (G1,G2,TP,TB,AMPT,AMPU,AMPS,ICLR)
      IMPLICIT NONE
      INTEGER ICLR
      DOUBLE COMPLEX G1(6),G2(6),TP(6),TB(6)
      DOUBLE COMPLEX AMPT,AMPU,AMPS,AMPT0,AMPU0
      DOUBLE COMPLEX W(6,3)
      include "coupl.inc"
      include "coupling.inc"
      INCLUDE "thr.inc"
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0D0)
      DOUBLE COMPLEX GAMMA
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      DOUBLE PRECISION COR,CORR
      EXTERNAL CORR
C.....
      IF (ITR.EQ.0) THEN
         COR = 1D0
      ELSEIF (ITR.EQ.1) THEN
         COR = CORR (MT1S,MT2S,TMASS,TWIDTH,gfermi,WMASS,BMASS)
      ENDIF
C.....
      CALL FVIXXX (TB,G2,GG,TMASS,TWIDTH,W(1,1))
      CALL IOVXXX (W(1,1),TP,G1,GG,AMPT) ! t-channel
      CALL FVIXXX (TB,G1,GG,TMASS,TWIDTH,W(1,2))
      CALL IOVXXX (W(1,2),TP,G2,GG,AMPU) ! u-channel
      CALL JVVXXX (G1,G2,G ,ZERO ,ZERO  ,W(1,3))
      CALL IOVXXX (TB,TP,W(1,3),GG,AMPS) ! s-channel
      IF ( IGRN.EQ.1 ) THEN     ! OCP
         CALL GRNMOD (GAMMA,MT1S,MT2S,S,TMASS,ICLR)
         AMPT = AMPT * ( COR*GAMMA + (1D0-COR) * DBLE(INR) )
         AMPU = AMPU * ( COR*GAMMA + (1D0-COR) * DBLE(INR) )
         AMPS = AMPS * ( COR*GAMMA + (1D0-COR) * DBLE(INR) )
      ELSEIF ( IGRN.EQ.2 ) THEN ! TAP
         CALL FVIXXZ (TB,G2,GG,TMASS,TWIDTH,W(1,1))
         CALL IOVXXX (W(1,1),TP,G1,GG,AMPT0) ! t-channel
         CALL FVIXXZ (TB,G1,GG,TMASS,TWIDTH,W(1,2))
         CALL IOVXXX (W(1,2),TP,G2,GG,AMPU0) ! u-channel
         CALL GRNMOD (GAMMA,MT1S,MT2S,S,TMASS,ICLR)
         AMPT = ( AMPT0*GAMMA + AMPT - AMPT0 ) * COR +
     -        AMPT*(1D0-COR) * DBLE(INR)
         AMPU = ( AMPU0*GAMMA + AMPU - AMPU0 ) * COR +
     -        AMPU*(1D0-COR) * DBLE(INR)
      ENDIF
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION CORR (S1,S2,MT,GT,GF,MW,MB)
      IMPLICIT NONE
      DOUBLE PRECISION S1,S2,MT,GT,GF,MW,MB
      DOUBLE PRECISION RUN,GT1,GT2
      EXTERNAL RUN
      GT1 = RUN(S1,MW,MB,GF)
      GT2 = RUN(S2,MW,MB,GF)
      CORR = DSQRT( MT*GT/(DSQRT(S1)*GT1) * MT*GT/(DSQRT(S2)*GT2) )
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION RUN (P2,MW,MB,GF)
      IMPLICIT NONE
      DOUBLE PRECISION P2,MW,MB,GF
      DOUBLE PRECISION X,Y,GT0,A0
      DOUBLE PRECISION PI,SQ2
      PARAMETER ( PI=3.141592654D0,SQ2=1.41421356D0)
      X = MW**2/P2
      Y = MB**2/P2
      GT0 = GF/(8D0*SQ2*PI) * P2**1.5
      A0 = (1D0-Y)**2 + X*(1D0+Y) - 2D0*X**2
      RUN = GT0 * A0 * DSQRT( 1D0 + X**2 + Y**2 - 2D0*(X+Y+X*Y) )
      RETURN
      END
C
      SUBROUTINE GRNMOD (GAMMA,ST,SX,S,MT,ICLR)
      IMPLICIT NONE
      DOUBLE COMPLEX GAMMA
      DOUBLE PRECISION ST,SX,S,MT
      INTEGER ICLR
      DOUBLE PRECISION E,P
      DOUBLE PRECISION LAM,A,B,C
      INTEGER IFLG
      DATA IFLG/0/
      SAVE IFLG
      LAM(A,B,C) = DSQRT(MAX(0D0,A**2+B**2+C**2-2D0*(A*B+B*C+C*A)))
      IF (IFLG.NE.99) CALL SETUPGRN (IFLG,MT)
      E = S/(4D0*MT) - MT
      P = DSQRT(S)/2D0 * LAM(1D0,ST/S,SX/S)
      CALL READGRN (GAMMA,E,P,ICLR)
      RETURN
      END
C
      SUBROUTINE SETUPGRN (IFLG,TMASS)
      IMPLICIT NONE
      INTEGER IFLG
      DOUBLE PRECISION TMASS
      INTEGER NE1,NP1,NE2,NP2
      DOUBLE PRECISION EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      CHARACTER*14 T1,T8,H1,H8
      COMMON/GRN1/NE1,NP1,NE2,NP2
      COMMON/GRN2/EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      COMMON/GRN3/T1,T8,H1,H8
      DATA NE1,NP1,NE2,NP2/800,300,400,101/
      DATA EMIN1,EMAX1,PMIN1,PMAX1/-50D0,30D0,0D0,300D0/
      DATA EMIN2,EMAX2,RR/30D0,830D0,0.9D0/
      DATA T1/"grnep1thre.tbl"/
      DATA T8/"grnep8thre.tbl"/
      DATA H1/"grnep1high.tbl"/
      DATA H8/"grnep8high.tbl"/
      DOUBLE PRECISION MT,MB,MW,GAMT
      COMMON/MASS/MT,MB,MW,GAMT
      DOUBLE PRECISION MUB,ASB
      COMMON/BOHR/MUB,ASB
      IFLG = 99
      MT = TMASS
      RETURN
      END
C
      SUBROUTINE READGRN (GAMMA,E,P,ICLR)
      IMPLICIT NONE
      INTEGER ICLR
      DOUBLE PRECISION E,P
      DOUBLE COMPLEX GRN,GAMMA
      INTEGER ITBL(2)
      DATA ITBL/0, 0/
      SAVE ITBL
      IF (ITBL(ICLR).NE.33) THEN
         CALL READTABLE (ICLR)
         ITBL (ICLR) = 33
      ENDIF
      CALL HOKAN2D (E,P,GRN,ICLR)
      GAMMA = GRN
      RETURN
      END
C
      SUBROUTINE READTABLE (ICLR)
      IMPLICIT NONE
      INTEGER IOF,ICLR
      PARAMETER (IOF=10)
      INTEGER ME,MP,IE,IP
      DOUBLE PRECISION R
      DOUBLE PRECISION RE,IM
      DOUBLE COMPLEX GRNEPT(0:2000,0:1000,2),GRNEPH(0:1000,0:1000,2)
      COMMON/GRN/GRNEPT,GRNEPH
      DOUBLE PRECISION MT,MB,MW,GAMT
      COMMON/MASS/MT,MB,MW,GAMT
      DOUBLE PRECISION MUB,ASB
      COMMON/BOHR/MUB,ASB
      DOUBLE PRECISION MMT,GGAMT,AASB
      CHARACTER*17 TT,HH
      INTEGER NE1,NP1,NE2,NP2
      DOUBLE PRECISION EMN,EMX,PMN,PMX
      DOUBLE PRECISION EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      COMMON/GRN1/NE1,NP1,NE2,NP2
      COMMON/GRN2/EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      CHARACTER*14 T1,T8,H1,H8
      COMMON/GRN3/T1,T8,H1,H8
      IF (ICLR.EQ.1) THEN
         TT = T1
         HH = H1
      ELSEIF (ICLR.EQ.2) THEN
         TT = T8
         HH = H8
      ELSE
         STOP
      ENDIF
C...  Read Thre tbl
      WRITE (9,*) "   Open file : ", TT
      OPEN (IOF,FILE=TT,STATUS="OLD",ERR=11)
      GOTO 12
 11   CONTINUE
      TT = "../" // TT
      OPEN (IOF,FILE=TT,STATUS="OLD",ERR=100)
 12   CONTINUE
      READ (IOF,*) MMT,GGAMT,AASB
      IF ( MT.EQ.MMT .AND. GAMT.EQ.GGAMT .AND. ASB.EQ.AASB ) THEN
      ELSE
         WRITE (9,*) "Parameters inconsistent", MT, GAMT, ASB
         WRITE (9,*) "           table (thre)",MMT,GGAMT,AASB
*         STOP
      ENDIF
      READ (IOF,*) ME, MP
      READ (IOF,*) EMN, EMX
      READ (IOF,*) PMN, PMX
      IF ( ME.EQ.NE1 .AND. MP.EQ.NP1 ) THEN
         DO IE = 0,NE1,1
            DO IP = 0,NP1,1
               READ (IOF,*) RE,IM
               GRNEPT (IE,IP,ICLR) = DCMPLX (RE,IM)
            ENDDO
            READ(IOF,*)
         ENDDO
      ELSE
         WRITE (9,*) "READGRN (thre): Incompatible Table Size"
         WRITE (9,*) "Table : ", ME, MP
         WRITE (9,*) "Inc :   ", NE1, NP1
         STOP
      ENDIF
      CLOSE (IOF)
C...  Read High tbl
      WRITE (9,*) "   Open file : ", HH
      OPEN (IOF,FILE=HH,STATUS="OLD",ERR=21)
      GOTO 22
 21   CONTINUE
      HH = "../" // HH
      OPEN (IOF,FILE=HH,STATUS="OLD",ERR=100)
 22   CONTINUE
      READ (IOF,*) MMT, GGAMT, AASB
      IF ( MT.EQ.MMT .AND. GAMT.EQ.GGAMT .AND. ASB.EQ.AASB ) THEN
      ELSE
         WRITE (9,*) "Parameters inconsistent", MT, GAMT, ASB
         WRITE (9,*) "           table (high)",MMT,GGAMT,AASB
*         STOP
      ENDIF
      READ (IOF,*) ME, MP
      READ (IOF,*) EMN, EMX
      READ (IOF,*) R
      IF ( ME.EQ.NE2 .AND. MP.EQ.NP2 .AND. R.EQ.RR ) THEN
         DO IE = 0,NE2,1
            DO IP = 0,NP2,1
               READ (IOF,*) RE,IM
               GRNEPH (IE,IP,ICLR) = DCMPLX (RE,IM)
            ENDDO
            READ(IOF,*)
         ENDDO
      ELSE
         WRITE (9,*) "READGRN (high): Incompatible Table Size"
         WRITE (9,*) "Table :", ME, MP, R
         WRITE (9,*) "Inc :  ", NE2, NP2, RR
         STOP
      ENDIF
      CLOSE (IOF)
      WRITE (9,*) ICLR, ": READTABLE"
      RETURN
 100  CONTINUE
      WRITE (1,*) "Error while opening GrnFnc table"
      WRITE (6,*) "Error while opening GrnFnc table"
      STOP
      END
C
      SUBROUTINE READGRNTBL (GREEN,IE,IP,ICLR,IT)
      IMPLICIT NONE
      INTEGER IE,IP,ICLR
      DOUBLE COMPLEX GREEN
      DOUBLE COMPLEX GRNEPT(0:2000,0:1000,1:2),GRNEPH(0:1000,0:1000,1:2)
      COMMON/GRN/GRNEPT,GRNEPH
      INTEGER IT
      IF (IT.EQ.1) THEN
         GREEN = GRNEPT (IE,IP,ICLR)
      ELSEIF (IT.EQ.2) THEN
         GREEN = GRNEPH (IE,IP,ICLR)
      ENDIF
      RETURN
      END
C
      SUBROUTINE HOKAN2D (EI,PI,GRN,ICLR)
      IMPLICIT NONE
      INTEGER IT
      DOUBLE PRECISION PMIN,PMAX
      INTEGER NE1,NP1,NE2,NP2
      DOUBLE PRECISION EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      COMMON/GRN1/NE1,NP1,NE2,NP2
      COMMON/GRN2/EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      DOUBLE PRECISION E,P,EI,PI
      INTEGER ICLR
      INTEGER IE,IP,IE0,IE1,IP0,IP1
      DOUBLE COMPLEX GRN
      INTEGER EINT,PINT
      DOUBLE PRECISION EE,PP
      EXTERNAL EINT,PINT,EE,PP
      DOUBLE PRECISION E0,E1,P0,P1
      DOUBLE COMPLEX G0,G1,G00,G01,G10,G11
      DOUBLE PRECISION MT,MB,MW,GAMT
      COMMON/MASS/MT,MB,MW,GAMT
      GRN = DCMPLX(1D0,0D0)
      IF (EI.LT.EMIN1 .OR. EI.GT.EMAX2) RETURN ! outside the grip
      IF (EI.LT.EMAX1) THEN
         IT = 1
         IF (EI.LT.EMIN1) THEN
            IE = 0
            E = EI
         ELSEIF (EI.GE.EMIN1) THEN
            E = EI
            IE = EINT(E,1)
         ELSE
            WRITE (9,*) "ERROR; IT = 1"
            STOP
         ENDIF
         PMIN = PMIN1
         PMAX = PMAX1
      ELSEIF (EI.GE.EMIN2) THEN
         IT = 2
         IF (EI.GT.EMAX2) THEN
C...  extrapolation
*            IE = NE2-1
*            E = EI
C...  stop at the maximum of grid
            E = EMAX2
            IE = NE2
         ELSEIF (EI.LE.EMAX2) THEN
            E = EI
            IE = EINT(E,2)
         ELSE
            WRITE (9,*) "ERROR; IT = 2"
            STOP
         ENDIF
         POS = DSQRT(MT*E)
         PMIN = PP (0,IT)
         PMAX = PP (NP2,IT)
      ELSE
         WRITE (9,*) "IT"
         WRITE(9,*) EI,EMIN1,EMAX1,EMIN2,EMAX2
         STOP
      ENDIF
C
      IF (PI.GT.PMAX) THEN
C...  extrapolation to outside grid
*         P = PI
*         IP = PINT(PMAX,IT) - 1
C...  stop at the maxmum
         P = PMAX
         IP = PINT(PMAX,IT)
      ELSEIF (PI.LT.PMIN) THEN
         P = PI
         IP = 0
      ELSE
         P = PI
         IP = PINT(P,IT)
      ENDIF
C
      IF (ABS(EE(IE,IT)-E).LE.1D-4 .AND. ABS(PP(IP,IT)-P).LE.1D-4) THEN
         CALL READGRNTBL (GRN,IE,IP,ICLR,IT)
*         WRITE (9,*) IE, IP, " On the Axes Inter-Section"
      ELSEIF ( ABS(PP(IP,IT)-P) .LE. 1D-4 ) THEN
         IE0 = IE
         IE1 = IE0 + 1
         E0 = EE(IE0,IT)
         E1 = EE(IE1,IT)
         CALL READGRNTBL (G0,IE0,IP,ICLR,IT)
         CALL READGRNTBL (G1,IE1,IP,ICLR,IT)
         GRN = (G1-G0)/(E1-E0)*(E-E0) + G0
*         WRITE (9,*) "On the P-Axis"
      ELSEIF ( ABS(EE(IE,IT)-E) .LE. 1D-4 ) THEN
         IP0 = IP
         IP1 = IP0 + 1
         P0 = PP(IP0,IT)
         P1 = PP(IP1,IT)
         CALL READGRNTBL (G0,IE,IP0,ICLR,IT)
         CALL READGRNTBL (G1,IE,IP1,ICLR,IT)
         GRN = (G1-G0)/(P1-P0)*(P-P0) + G0
*         WRITE (9,*) "On the E-Axis"
      ELSE
         IE0 = IE
         IE1 = IE0 + 1
         E0 = EE(IE0,IT)
         E1 = EE(IE1,IT)
         IP0 = IP
         IP1 = IP0 + 1
         P0 = PP(IP0,IT)
         P1 = PP(IP1,IT)
         CALL READGRNTBL (G00,IE0,IP0,ICLR,IT)
         CALL READGRNTBL (G01,IE0,IP1,ICLR,IT)
         G0 = (G01-G00)/(P1-P0)*(P-P0) + G00
         CALL READGRNTBL (G10,IE1,IP0,ICLR,IT)
         CALL READGRNTBL (G11,IE1,IP1,ICLR,IT)
         G1 = (G11-G10)/(P1-P0)*(P-P0) + G10
         GRN = (G1-G0)/(E1-E0)*(E-E0) + G0
      ENDIF
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION EE (IE,IT)
      IMPLICIT NONE
      INTEGER IT,NE
      DOUBLE PRECISION EMIN,EMAX
      INTEGER NE1,NP1,NE2,NP2
      DOUBLE PRECISION EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      COMMON/GRN1/NE1,NP1,NE2,NP2
      COMMON/GRN2/EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      INTEGER IE
      IF (IT.EQ.1) THEN
         NE = NE1
         EMIN = EMIN1
         EMAX = EMAX1
      ELSEIF (IT.EQ.2) THEN
         NE = NE2
         EMIN = EMIN2
         EMAX = EMAX2
      ENDIF
      EE = EMIN + DBLE(IE)/DBLE(NE) * (EMAX - EMIN)
      RETURN
      END
C
      INTEGER FUNCTION EINT (E,IT)
      IMPLICIT NONE
      INTEGER IT,NE
      DOUBLE PRECISION EMIN,EMAX
      INTEGER NE1,NP1,NE2,NP2
      DOUBLE PRECISION EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      COMMON/GRN1/NE1,NP1,NE2,NP2
      COMMON/GRN2/EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      DOUBLE PRECISION E
      IF (IT.EQ.1) THEN
         NE = NE1
         EMIN = EMIN1
         EMAX = EMAX1
      ELSEIF (IT.EQ.2) THEN
         NE = NE2
         EMIN = EMIN2
         EMAX = EMAX2
      ENDIF
      EINT = INT(NE*(E-EMIN)/(EMAX-EMIN))
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION PP (IP,IT)
      IMPLICIT NONE
      INTEGER IP,IT,M
      DOUBLE PRECISION PMIN,PMAX
      DOUBLE PRECISION A,R1
      INTEGER NE1,NP1,NE2,NP2
      DOUBLE PRECISION EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      COMMON/GRN1/NE1,NP1,NE2,NP2
      COMMON/GRN2/EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      IF (IT.EQ.1) THEN
         PMIN = PMIN1
         PMAX = PMAX1
         PP = PMIN + DBLE(IP)/DBLE(NP1) * (PMAX - PMIN)
      ELSEIF (IT.EQ.2) THEN
         M = (NP2-1)/2
         A = (1D0-RR)/(1D0-RR**M) * POS
         R1 = 1D0/RR
         IF (IP.LE.M) THEN
            PP = POS * (1D0-RR**(IP+1)) / (1D0-RR**(M+1))
         ELSE
            PP = POS + A*RR**M*(1D0-R1**(IP-M+1))/(1D0-R1)
         ENDIF
      ENDIF
      RETURN
      END
C
      INTEGER FUNCTION PINT (P,IT)
      IMPLICIT NONE
      DOUBLE PRECISION P,A,R1
      INTEGER IT,M
      DOUBLE PRECISION PMIN,PMAX
      INTEGER NE1,NP1,NE2,NP2
      DOUBLE PRECISION EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      COMMON/GRN1/NE1,NP1,NE2,NP2
      COMMON/GRN2/EMIN1,EMAX1,PMIN1,PMAX1,EMIN2,EMAX2,RR,POS
      IF (IT.EQ.1) THEN
         PMIN = PMIN1
         PMAX = PMAX1
         PINT = INT(NP1*(P-PMIN)/(PMAX-PMIN))
      ELSEIF (IT.EQ.2) THEN
         M = (NP2-1)/2
         A = (1D0-RR)/(1D0-RR**M) * POS
         R1 = 1D0/RR
         IF (P.LE.POS) THEN
            PINT = INT(DLOG(1D0-P/POS*(1D0-RR**(M+1)))/DLOG(RR)) - 1
         ELSE
            PINT = INT(DLOG(1D0-(P-POS)/(A*RR**M)*(1D0-R1))/DLOG(R1))
     -           + M - 1
         ENDIF
      ENDIF
      RETURN
      END
c
      subroutine fvixxz (fi,vc,gc,fmass,fwidth , fvi)
c
c This subroutine computes an off-shell fermion wavefunction from a
c flowing-IN external fermion and a vector boson.
c
c input:
c     complex fi(6)          : flow-in  fermion                   |fi>
c     complex vc(6)          : input    vector                      v
c     complex gc(2)          : coupling constants                  gvf
c     real    fmass          : mass  of output fermion f'
c     real    fwidth         : width of output fermion f'
c
c output:
c     complex fvi(6)         : off-shell fermion             |f',v,fi>
c
      implicit none
      double complex fi(6),vc(6),gc(2),fvi(6),sl1,sl2,sr1,sr2,d
      double precision pf(0:3),fmass,fwidth,pf2,pab
      double precision rZero, rOne
      parameter( rZero = 0.0d0, rOne = 1.0d0 )
      double complex cImag, cZero
      parameter( cImag = ( 0.0d0, 1.0d0 ), cZero = ( 0.0d0, 0.0d0 ) )
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      DOUBLE PRECISION DEL,LM,LAM
      EXTERNAL LAM
      DOUBLE PRECISION D1,D2
c
      integer stdo
      parameter( stdo = 6 )
c
      if ( abs(fi(1))+abs(fi(2))+abs(fi(3))+abs(fi(4)).eq.rZero ) then
         write(stdo,*) ' helas-warn  : fi in fvixxx is zero spinor'
      endif
      if ( abs(fi(5))+abs(fi(6)).eq.rZero ) then
         write(stdo,*)
     &        ' helas-error : fi in fvixxx has zero momentum'
      endif
      if ( abs(vc(1))+abs(vc(2))+abs(vc(3))+abs(vc(4)).eq.rZero ) then
         write(stdo,*) ' helas-warn  : vc in fvixxx is zero vector'
      endif
      if ( abs(vc(5))+abs(vc(6)).eq.rZero ) then
         write(stdo,*)
     &        ' helas-error : vc in fvixxx has zero momentum'
      endif
      if ( gc(1).eq.cZero .and. gc(2).eq.cZero ) then
         write(stdo,*)
     &        ' helas-error : gc in fvixxx is zero coupling'
      endif
      if ( fmass.lt.rZero ) then
         write(stdo,*) ' helas-error : fmass in fvixxx is negative'
         write(stdo,*) '             : fmass = ',fmass
      endif
      if ( fwidth.lt.rZero ) then
         write(stdo,*) ' helas-error : fwidth in fvixxx is negative'
         write(stdo,*) '             : fwidth = ',fwidth
      endif

      fvi(5) = fi(5) - vc(5)
      fvi(6) = fi(6) - vc(6)

      pf(0) = dble( fvi(5))
      pf(1) = dble( fvi(6))
      pf(2) = dimag(fvi(6))
      pf(3) = dimag(fvi(5))
      pf2 = pf(0)**2-(pf(1)**2+pf(2)**2+pf(3)**2)

      if ( abs(fvi(5))+abs(fvi(6)).eq.rZero ) then
         write(stdo,*)
     &        ' helas-error : fvi in fvixxx has zero momentum'
      endif
      if ( fwidth.eq.rZero .and. pf2.eq.fmass**2 ) then
         write(stdo,*)
     &        ' helas-error : fvi in fvixxx is on fmass pole'
         write(stdo,*)
     &        '             : p     = ',pf(0),pf(1),pf(2),pf(3)
         write(stdo,*)
     &        '             : abs(p)= ',dsqrt(dabs(pf2))
         fvi(1) = cZero
         fvi(2) = cZero
         fvi(3) = cZero
         fvi(4) = cZero
         return
      endif

      del = (2.*fmass**2 - MT1S - MT2S) / S
      lm = LAM(rOne,MT1S/S,MT2S/S)
      d1 = rOne / (S * lm) * dlog((rOne+del+lm)/(rOne+del-lm))
      d2 = rOne / (S * lm) *
     -     (2. -(rOne+del) * dlog((rOne+del+lm)/(rOne+del-lm)))

      pab = dsqrt(dble(fi(6))**2+dimag(fi(6))**2+dimag(fi(5))**2)

      pf(0) = dble(fi(5) - vc(5)) * d1
      pf(1) = dble(      - vc(6)) * d1
      pf(2) = dimag(     - vc(6)) * d1
      pf(3) = dimag(     - vc(5)) * d1
*      pf(3) = dimag(-pab*d2 - vc(5)*d1)
c
      sl1 =  (vc(1) +       vc(4)) * fi(1)
     &     + (vc(2) - cImag*vc(3)) * fi(2)
      sl2 =  (vc(2) + cImag*vc(3)) * fi(1)
     &     + (vc(1) -       vc(4)) * fi(2)
c
      sr1 =   (vc(1) -       vc(4)) * fi(3)
     &     -  (vc(2) - cImag*vc(3)) * fi(4)
      sr2 = - (vc(2) + cImag*vc(3)) * fi(3)
     &     +  (vc(1) +       vc(4)) * fi(4)
c
      fvi(1) = ( gc(1)*( (pf(0)-pf(3))*sl1 - (pf(1)-cImag*pf(2))*sl2)
     &     + gc(2)*fmass*sr1 * d1 )
      fvi(2) = ( gc(1)*(-(pf(1)+cImag*pf(2))*sl1 + (pf(0)+pf(3))*sl2)
     &     + gc(2)*fmass*sr2 * d1 )
      fvi(3) = ( gc(2)*( (pf(0)+pf(3))*sr1 + (pf(1)-cImag*pf(2))*sr2)
     &     + gc(1)*fmass*sl1 * d1 )
      fvi(4) = ( gc(2)*( (pf(1)+cImag*pf(2))*sr1 + (pf(0)-pf(3))*sr2)
     &     + gc(1)*fmass*sl2 * d1 )
c
      return
      end
c
c
      DOUBLE PRECISION FUNCTION LAM (A,B,C)
      IMPLICIT NONE
      DOUBLE PRECISION A,B,C
      LAM = DSQRT(MAX(A**2+B**2+C**2-2D0*A*B-2D0*B*C-2D0*C*A, 0D0))
      RETURN
      END
