      DOUBLE PRECISION FUNCTION CORR (S1,S2,MT,GT,GF,MW,MB)
      IMPLICIT NONE
      DOUBLE PRECISION S1,S2,MT,GT,GF,MW,MB
      DOUBLE PRECISION RUN,GT1,GT2
      EXTERNAL RUN
      GT1 = RUN(S1,MW,MB,GF)
      GT2 = RUN(S2,MW,MB,GF)
      CORR = DSQRT( MT*GT/(DSQRT(S1)*GT1) * MT*GT/(DSQRT(S2)*GT2) )
      RETURN
      END
C
      DOUBLE PRECISION FUNCTION RUN (P2,MW,MB,GF)
      IMPLICIT NONE
      DOUBLE PRECISION P2,MW,MB,GF
      DOUBLE PRECISION X,Y,GT0,A0
      DOUBLE PRECISION PI,SQ2
      PARAMETER ( PI=3.141592654D0,SQ2=1.41421356D0)
      X = MW**2/P2
      Y = MB**2/P2
      GT0 = GF/(8D0*SQ2*PI) * P2**1.5
      A0 = (1D0-Y)**2 + X*(1D0+Y) - 2D0*X**2
      RUN = GT0 * A0 * DSQRT( 1D0 + X**2 + Y**2 - 2D0*(X+Y+X*Y) )
      RETURN
      END
