      CHARACTER*18 T1,T8,H1,H8
      PARAMETER (T1="./grnep1thre.tbl")
      PARAMETER (T8="./grnep8thre.tbl")
      PARAMETER (H1="./grnep1high.tbl")
      PARAMETER (H8="./grnep8high.tbl")
*      CHARACTER*130 T1,T8,H1,H8
*      PARAMETER (T1="/afs/cern.ch/user/y/yokoya/Work/TTExcl/Fortran/MKTBL/grnep1thre.tbl")
*      PARAMETER (T8="/afs/cern.ch/user/y/yokoya/Work/TTExcl/Fortran/MKTBL/grnep8thre.tbl")
*      PARAMETER (H1="/afs/cern.ch/user/y/yokoya/Work/TTExcl/Fortran/MKTBL/grnep1high.tbl")
*      PARAMETER (H8="/afs/cern.ch/user/y/yokoya/Work/TTExcl/Fortran/MKTBL/grnep8high.tbl")
