      SUBROUTINE GGTTRES (G1,G2,TP,TB,AMPT,AMPU,AMPS,ICLR)
      IMPLICIT NONE
      INTEGER ICLR
      DOUBLE COMPLEX G1(6),G2(6),TP(6),TB(6)
      DOUBLE COMPLEX AMPT,AMPU,AMPS,AMPT0,AMPU0
      DOUBLE COMPLEX W(6,3)
      include "coupl_sm.inc"
      INCLUDE "thr.inc"
      DOUBLE PRECISION ZERO
      PARAMETER (ZERO=0D0)
      DOUBLE COMPLEX GAMMA
      DOUBLE PRECISION MT1S,MT2S,S
      COMMON/BW/MT1S,MT2S,S
      DOUBLE PRECISION COR,CORR
      EXTERNAL CORR
      DOUBLE PRECISION FNR(0:2)
      DATA FNR/0.,1.,1./
C.....
      IF (ITR.EQ.0) THEN
         COR = 1D0
      ELSEIF (ITR.EQ.1) THEN
         COR = CORR (MT1S,MT2S,TMASS,TWIDTH,gfermi,WMASS,BMASS)
      ENDIF
C.....
      CALL FVIXXX (TB,G2,GG,TMASS,TWIDTH,W(1,1))
      CALL IOVXXX (W(1,1),TP,G1,GG,AMPT) ! t-channel
      CALL FVIXXX (TB,G1,GG,TMASS,TWIDTH,W(1,2))
      CALL IOVXXX (W(1,2),TP,G2,GG,AMPU) ! u-channel
      CALL JVVXXX (G1,G2,G ,ZERO ,ZERO  ,W(1,3))
      CALL IOVXXX (TB,TP,W(1,3),GG,AMPS) ! s-channel
      IF ( IGRN.EQ.1 ) THEN     ! OCP
         CALL GRNMOD (GAMMA,MT1S,MT2S,S,TMASS,ICLR,IGRN)
         AMPT = AMPT * ( COR*GAMMA + (1D0-COR) * FNR(INR) )
         AMPU = AMPU * ( COR*GAMMA + (1D0-COR) * FNR(INR) )
         AMPS = AMPS * ( COR*GAMMA + (1D0-COR) * FNR(INR) )
      ELSEIF ( IGRN.EQ.2 ) THEN ! TAP
         CALL FVIXXZ (TB,G2,GG,TMASS,TWIDTH,W(1,1))
         CALL IOVXXX (W(1,1),TP,G1,GG,AMPT0) ! t-channel
         CALL FVIXXZ (TB,G1,GG,TMASS,TWIDTH,W(1,2))
         CALL IOVXXX (W(1,2),TP,G2,GG,AMPU0) ! u-channel
         CALL GRNMOD (GAMMA,MT1S,MT2S,S,TMASS,ICLR,IGRN)
         AMPT = ( AMPT0*GAMMA + AMPT - AMPT0 ) * COR +
     -        AMPT*(1D0-COR) * FNR(INR)
         AMPU = ( AMPU0*GAMMA + AMPU - AMPU0 ) * COR +
     -        AMPU*(1D0-COR) * FNR(INR)
      ENDIF
      RETURN
      END
