        INTEGER IGRN,ITR,INR
	COMMON/THR/IGRN,ITR,INR
C...... IGRN .........................................
C        0: No Coulomb correction,
C        1: Overall correction prescription,
C        2: Total angular momentum prescription
C...... INR ..........................................
C        0: No non-factorizable diagrams
C        1: Fixed Width Scheme
C        2: Overall Factor Scheme
C...... ITR ..........................................
C        0: Naive diagramatic separation
C        1: Removing PS suppression in resonant amplitude
C.....................................................
